if (gradle.parent == null) { throw new GradleException("This project should not be built directly. Please build the entire SDK from the main build-android folder in the root.") }
rootProject.name='VulkanHelloAPI'

//Copy all the build output stuff into the SDK/bin folder
gradle.ext.PVR_BINARY_OUTPUT_DIR='bin'
