plugins { id 'com.android.library' }

android {
namespace = "com.powervr.PVRUtilsGles"
defaultConfig {
versionCode = 1
versionName = "1.0"
		externalNativeBuild {
			cmake {
				cppFlags "-fexceptions"
				arguments "-DANDROID_STL=c++_static", "-DPVR_PREBUILT_DEPENDENCIES=ON", "-DPVR_ENABLE_INSTALL=ON"
				targets "PVRUtilsGles"
			}
		}
}
	externalNativeBuild {
		cmake {

			path = "../CMakeLists.txt"
}
	}
}

dependencies {
    implementation project(':PVRShell')
    implementation project(':PVRAssets')
}

