/*!*********************************************************************************************************************
\file         PVRNativeApi\OGLES\LibraryLoaderGles.cpp
\author       PowerVR by Imagination, Developer Technology Team
\copyright    Copyright (c) Imagination Technologies Limited.
\brief         Implementation of the PowerVR OpenGL ES bindings (gl:: namespace).
***********************************************************************************************************************/
//!\cond NO_DOXYGEN
#include "LibraryLoaderGles.h"
#include "ExtensionLoaderGles.h"
#include <memory>
#include <PVRCore/Log.h>

#ifdef _WIN32
static const char* libName = "libGLESv2.dll";
#elif defined(TARGET_OS_MAC)
static const char* libName = "libGLESv2.dylib";
#else
static const char* libName = "libGLESv2.so";
#endif
#ifndef TARGET_OS_IPHONE
static pvr::native::NativeLibrary& glesLibrary()
{
	static pvr::native::NativeLibrary mylib(libName);
	return mylib;
}

extern bool isOpenGLES31NotSupported_Workaround;

static bool dummy = isOpenGLES31NotSupported_Workaround = !glesLibrary().getFunction<PROC_ES31_glDispatchCompute>("glDispatchCompute");

#endif
void gl::releaseGl()
{
#ifndef TARGET_OS_IPHONE
	//STANDARD GUARANTEES ZERO-INITIALIZATION for static members.
	gl::ActiveTexture = 0;
	gl::AttachShader = 0;
	gl::BindAttribLocation = 0;
	gl::BindBuffer = 0;
	gl::BindFramebuffer = 0;
	gl::BindRenderbuffer = 0;
	gl::BindTexture = 0;
	gl::BlendColor = 0;
	gl::BlendEquation = 0;
	gl::BlendEquationSeparate = 0;
	gl::BlendFunc = 0;
	gl::BlendFuncSeparate = 0;
	gl::BufferData = 0;
	gl::BufferSubData = 0;
	gl::CheckFramebufferStatus = 0;
	gl::Clear = 0;
	gl::ClearColor = 0;
	gl::ClearDepthf = 0;
	gl::ClearStencil = 0;
	gl::ColorMask = 0;
	gl::CompileShader = 0;
	gl::CompressedTexImage2D = 0;
	gl::CompressedTexSubImage2D = 0;
	gl::CopyTexImage2D = 0;
	gl::CopyTexSubImage2D = 0;
	gl::CreateProgram = 0;
	gl::CreateShader = 0;
	gl::CullFace = 0;
	gl::DeleteBuffers = 0;
	gl::DeleteFramebuffers = 0;
	gl::DeleteTextures = 0;
	gl::DeleteProgram = 0;
	gl::DeleteRenderbuffers = 0;
	gl::DeleteShader = 0;
	gl::DetachShader = 0;
	gl::DepthFunc = 0;
	gl::DepthMask = 0;
	gl::DepthRangef = 0;
	gl::Disable = 0;
	gl::DisableVertexAttribArray = 0;
	gl::DrawArrays = 0;
	gl::DrawElements = 0;
	gl::Enable = 0;
	gl::EnableVertexAttribArray = 0;
	gl::Finish = 0;
	gl::Flush = 0;
	gl::FramebufferRenderbuffer = 0;
	gl::FramebufferTexture2D = 0;
	gl::FrontFace = 0;
	gl::GenBuffers = 0;
	gl::GenerateMipmap = 0;
	gl::GenFramebuffers = 0;
	gl::GenRenderbuffers = 0;
	gl::GenTextures = 0;
	gl::GetActiveAttrib = 0;
	gl::GetActiveUniform = 0;
	gl::GetAttachedShaders = 0;
	gl::GetAttribLocation = 0;
	gl::GetBooleanv = 0;
	gl::GetBufferParameteriv = 0;
	gl::GetError = 0;
	gl::GetFloatv = 0;
	gl::GetFramebufferAttachmentParameteriv = 0;
	gl::GetIntegerv = 0;
	gl::GetProgramiv = 0;
	gl::GetProgramInfoLog = 0;
	gl::GetRenderbufferParameteriv = 0;
	gl::GetShaderiv = 0;
	gl::GetShaderInfoLog = 0;
	gl::GetShaderPrecisionFormat = 0;
	gl::GetShaderSource = 0;
	gl::GetString = 0;
	gl::GetTexParameterfv = 0;
	gl::GetTexParameteriv = 0;
	gl::GetUniformfv = 0;
	gl::GetUniformiv = 0;
	gl::GetUniformLocation = 0;
	gl::GetVertexAttribfv = 0;
	gl::GetVertexAttribiv = 0;
	gl::GetVertexAttribPointerv = 0;
	gl::Hint = 0;
	gl::IsBuffer = 0;
	gl::IsEnabled = 0;
	gl::IsFramebuffer = 0;
	gl::IsProgram = 0;
	gl::IsRenderbuffer = 0;
	gl::IsShader = 0;
	gl::IsTexture = 0;
	gl::LineWidth = 0;
	gl::LinkProgram = 0;
	gl::PixelStorei = 0;
	gl::PolygonOffset = 0;
	gl::ReadPixels = 0;
	gl::ReleaseShaderCompiler = 0;
	gl::RenderbufferStorage = 0;
	gl::SampleCoverage = 0;
	gl::Scissor = 0;
	gl::ShaderBinary = 0;
	gl::ShaderSource = 0;
	gl::StencilFunc = 0;
	gl::StencilFuncSeparate = 0;
	gl::StencilMask = 0;
	gl::StencilMaskSeparate = 0;
	gl::StencilOp = 0;
	gl::StencilOpSeparate = 0;
	gl::TexImage2D = 0;
	gl::TexParameterf = 0;
	gl::TexParameterfv = 0;
	gl::TexParameteri = 0;
	gl::TexParameteriv = 0;
	gl::TexSubImage2D = 0;
	gl::Uniform1f = 0;
	gl::Uniform1fv = 0;
	gl::Uniform1i = 0;
	gl::Uniform1iv = 0;
	gl::Uniform2f = 0;
	gl::Uniform2fv = 0;
	gl::Uniform2i = 0;
	gl::Uniform2iv = 0;
	gl::Uniform3f = 0;
	gl::Uniform3fv = 0;
	gl::Uniform3i = 0;
	gl::Uniform3iv = 0;
	gl::Uniform4f = 0;
	gl::Uniform4fv = 0;
	gl::Uniform4i = 0;
	gl::Uniform4iv = 0;
	gl::UniformMatrix2fv = 0;
	gl::UniformMatrix3fv = 0;
	gl::UniformMatrix4fv = 0;
	gl::UseProgram = 0;
	gl::ValidateProgram = 0;
	gl::VertexAttrib1f = 0;
	gl::VertexAttrib1fv = 0;
	gl::VertexAttrib2f = 0;
	gl::VertexAttrib2fv = 0;
	gl::VertexAttrib3f = 0;
	gl::VertexAttrib3fv = 0;
	gl::VertexAttrib4f = 0;
	gl::VertexAttrib4fv = 0;
	gl::VertexAttribPointer = 0;
	gl::Viewport = 0;

#if BUILD_API_MAX>=30
	// Es3 functions
	gl::ReadBuffer = 0;
	gl::DrawRangeElements = 0;
	gl::TexImage3D = 0;
	gl::TexSubImage3D = 0;
	gl::CopyTexSubImage3D = 0;
	gl::CompressedTexImage3D = 0;
	gl::CompressedTexSubImage3D = 0;
	gl::GenQueries = 0;
	gl::DeleteQueries = 0;
	gl::IsQuery = 0;
	gl::BeginQuery = 0;
	gl::EndQuery = 0;
	gl::GetQueryiv = 0;
	gl::GetQueryObjectuiv = 0;
	gl::UnmapBuffer = 0;
	gl::GetBufferPointerv = 0;
	gl::DrawBuffers = 0;
	gl::UniformMatrix2x3fv = 0;
	gl::UniformMatrix3x2fv = 0;
	gl::UniformMatrix2x4fv = 0;
	gl::UniformMatrix4x2fv = 0;
	gl::UniformMatrix3x4fv = 0;
	gl::UniformMatrix4x3fv = 0;
	gl::BlitFramebuffer = 0;
	gl::RenderbufferStorageMultisample = 0;
	gl::FramebufferTextureLayer = 0;
	gl::MapBufferRange = 0;
	gl::FlushMappedBufferRange = 0;
	gl::BindVertexArray = 0;
	gl::DeleteVertexArrays = 0;
	gl::GenVertexArrays = 0;
	gl::IsVertexArray = 0;
	gl::GetIntegeri_v = 0;
	gl::BeginTransformFeedback = 0;
	gl::EndTransformFeedback = 0;
	gl::BindBufferRange = 0;
	gl::BindBufferBase = 0;
	gl::TransformFeedbackVaryings = 0;
	gl::GetTransformFeedbackVarying = 0;
	gl::VertexAttribIPointer = 0;
	gl::GetVertexAttribIiv = 0;
	gl::GetVertexAttribIuiv = 0;
	gl::VertexAttribI4i = 0;
	gl::VertexAttribI4ui = 0;
	gl::VertexAttribI4iv = 0;
	gl::VertexAttribI4uiv = 0;
	gl::GetUniformuiv = 0;
	gl::GetFragDataLocation = 0;
	gl::Uniform1ui = 0;
	gl::Uniform2ui = 0;
	gl::Uniform3ui = 0;
	gl::Uniform4ui = 0;
	gl::Uniform1uiv = 0;
	gl::Uniform2uiv = 0;
	gl::Uniform3uiv = 0;
	gl::Uniform4uiv = 0;
	gl::ClearBufferiv = 0;
	gl::ClearBufferuiv = 0;
	gl::ClearBufferfv = 0;
	gl::ClearBufferfi = 0;
	gl::GetStringi = 0;
	gl::CopyBufferSubData = 0;
	gl::GetUniformIndices = 0;
	gl::GetActiveUniformsiv = 0;
	gl::GetUniformBlockIndex = 0;
	gl::GetActiveUniformBlockiv = 0;
	gl::GetActiveUniformBlockName = 0;
	gl::UniformBlockBinding = 0;
	gl::DrawArraysInstanced = 0;
	gl::DrawElementsInstanced = 0;
	gl::FenceSync = 0;
	gl::IsSync = 0;
	gl::DeleteSync = 0;
	gl::ClientWaitSync = 0;
	gl::WaitSync = 0;
	gl::GetInteger64v = 0;
	gl::GetSynciv = 0;
	gl::GetInteger64i_v = 0;
	gl::GetBufferParameteri64v = 0;
	gl::GenSamplers = 0;
	gl::DeleteSamplers = 0;
	gl::IsSampler = 0;
	gl::BindSampler = 0;
	gl::SamplerParameteri = 0;
	gl::SamplerParameteriv = 0;
	gl::SamplerParameterf = 0;
	gl::SamplerParameterfv = 0;
	gl::GetSamplerParameteriv = 0;
	gl::GetSamplerParameterfv = 0;
	gl::VertexAttribDivisor = 0;
	gl::BindTransformFeedback = 0;
	gl::DeleteTransformFeedbacks = 0;
	gl::GenTransformFeedbacks = 0;
	gl::IsTransformFeedback = 0;
	gl::PauseTransformFeedback = 0;
	gl::ResumeTransformFeedback = 0;
	gl::GetProgramBinary = 0;
	gl::ProgramBinary = 0;
	gl::ProgramParameteri = 0;
	gl::InvalidateFramebuffer = 0;
	gl::InvalidateSubFramebuffer = 0;
	gl::TexStorage2D = 0;
	gl::TexStorage3D = 0;
	gl::GetInternalformativ = 0;
#endif

#if BUILD_API_MAX>=31
	// Es3.1 functions
	gl::DispatchCompute = 0;
	gl::DispatchComputeIndirect = 0;
	gl::BindImageTexture = 0;
	gl::MemoryBarrier = 0;
	gl::MemoryBarrierByRegion = 0;
	gl::BindProgramPipeline = 0;
	gl::DeleteProgramPipelines = 0;
	gl::GenProgramPipelines = 0;
	gl::IsProgramPipeline = 0;
	gl::GetProgramPipelineiv = 0;
	gl::ValidateProgramPipeline = 0;
	gl::GetProgramPipelineInfoLog = 0;
	gl::UseProgramStages = 0;
	gl::ActiveShaderProgram = 0;
	gl::ProgramUniform1i = 0;
	gl::ProgramUniform2i = 0;
	gl::ProgramUniform3i = 0;
	gl::ProgramUniform4i = 0;
	gl::ProgramUniform1ui = 0;
	gl::ProgramUniform2ui = 0;
	gl::ProgramUniform3ui = 0;
	gl::ProgramUniform4ui = 0;
	gl::ProgramUniform1f = 0;
	gl::ProgramUniform2f = 0;
	gl::ProgramUniform3f = 0;
	gl::ProgramUniform4f = 0;
	gl::ProgramUniform1iv = 0;
	gl::ProgramUniform2iv = 0;
	gl::ProgramUniform3iv = 0;
	gl::ProgramUniform4iv = 0;
	gl::ProgramUniform1uiv = 0;
	gl::ProgramUniform2uiv = 0;
	gl::ProgramUniform3uiv = 0;
	gl::ProgramUniform4uiv = 0;
	gl::ProgramUniform1fv = 0;
	gl::ProgramUniform2fv = 0;
	gl::ProgramUniform3fv = 0;
	gl::ProgramUniform4fv = 0;
	gl::ProgramUniformMatrix2fv = 0;
	gl::ProgramUniformMatrix3fv = 0;
	gl::ProgramUniformMatrix4fv = 0;
	gl::ProgramUniformMatrix2x3fv = 0;
	gl::ProgramUniformMatrix3x2fv = 0;
	gl::ProgramUniformMatrix2x4fv = 0;
	gl::ProgramUniformMatrix4x2fv = 0;
	gl::ProgramUniformMatrix3x4fv = 0;
	gl::ProgramUniformMatrix4x3fv = 0;
	gl::CreateShaderProgramv = 0;
	gl::DrawArraysIndirect = 0;
	gl::DrawElementsIndirect = 0;
	gl::TexStorage2DMultisample = 0;
	gl::SampleMaski = 0;
	gl::BindVertexBuffer = 0;
	gl::VertexAttribFormat = 0;
	gl::VertexAttribIFormat = 0;
	gl::VertexAttribBinding = 0;
	gl::VertexBindingDivisor = 0;
	gl::FramebufferParameteri = 0;
	gl::GetFramebufferParameteriv = 0;
	gl::GetProgramInterfaceiv = 0;
	gl::GetProgramResourceIndex = 0;
	gl::GetProgramResourceName = 0;
	gl::GetProgramResourceiv = 0;
	gl::GetProgramResourceLocation = 0;
	gl::GetBooleani_v = 0;
	gl::GetMultisamplefv = 0;
	gl::GetTexLevelParameteriv = 0;
	gl::GetTexLevelParameterfv = 0;
#endif
#endif
}

void gl::initGl()
{
#ifndef TARGET_OS_IPHONE
	// Load ES2 functionality
	gl::ActiveTexture = glesLibrary().getFunction<PROC_ES2_glActiveTexture>("glActiveTexture");
	gl::AttachShader = glesLibrary().getFunction<PROC_ES2_glAttachShader>("glAttachShader");
	gl::BindAttribLocation = glesLibrary().getFunction<PROC_ES2_glBindAttribLocation>("glBindAttribLocation");
	gl::BindBuffer = glesLibrary().getFunction<PROC_ES2_glBindBuffer>("glBindBuffer");
	gl::BindFramebuffer = glesLibrary().getFunction<PROC_ES2_glBindFramebuffer>("glBindFramebuffer");
	gl::BindRenderbuffer = glesLibrary().getFunction<PROC_ES2_glBindRenderbuffer>("glBindRenderbuffer");
	gl::BindTexture = glesLibrary().getFunction<PROC_ES2_glBindTexture>("glBindTexture");
	gl::BlendColor = glesLibrary().getFunction<PROC_ES2_glBlendColor>("glBlendColor");
	gl::BlendEquation = glesLibrary().getFunction<PROC_ES2_glBlendEquation>("glBlendEquation");
	gl::BlendEquationSeparate = glesLibrary().getFunction<PROC_ES2_glBlendEquationSeparate>("glBlendEquationSeparate");
	gl::BlendFunc = glesLibrary().getFunction<PROC_ES2_glBlendFunc>("glBlendFunc");
	gl::BlendFuncSeparate = glesLibrary().getFunction<PROC_ES2_glBlendFuncSeparate>("glBlendFuncSeparate");
	gl::BufferData = glesLibrary().getFunction<PROC_ES2_glBufferData>("glBufferData");
	gl::BufferSubData = glesLibrary().getFunction<PROC_ES2_glBufferSubData>("glBufferSubData");
	gl::CheckFramebufferStatus = glesLibrary().getFunction<PROC_ES2_glCheckFramebufferStatus>("glCheckFramebufferStatus");
	gl::Clear = glesLibrary().getFunction<PROC_ES2_glClear>("glClear");
	gl::ClearColor = glesLibrary().getFunction<PROC_ES2_glClearColor>("glClearColor");
	gl::ClearDepthf = glesLibrary().getFunction<PROC_ES2_glClearDepthf>("glClearDepthf");
	gl::ClearStencil = glesLibrary().getFunction<PROC_ES2_glClearStencil>("glClearStencil");
	gl::ColorMask = glesLibrary().getFunction<PROC_ES2_glColorMask>("glColorMask");
	gl::CompileShader = glesLibrary().getFunction<PROC_ES2_glCompileShader>("glCompileShader");
	gl::CompressedTexImage2D = glesLibrary().getFunction<PROC_ES2_glCompressedTexImage2D>("glCompressedTexImage2D");
	gl::CompressedTexSubImage2D = glesLibrary().getFunction<PROC_ES2_glCompressedTexSubImage2D>("glCompressedTexSubImage2D");
	gl::CopyTexImage2D = glesLibrary().getFunction<PROC_ES2_glCopyTexImage2D>("glCopyTexImage2D");
	gl::CopyTexSubImage2D = glesLibrary().getFunction<PROC_ES2_glCopyTexSubImage2D>("glCopyTexSubImage2D");
	gl::CreateProgram = glesLibrary().getFunction<PROC_ES2_glCreateProgram>("glCreateProgram");
	gl::CreateShader = glesLibrary().getFunction<PROC_ES2_glCreateShader>("glCreateShader");
	gl::CullFace = glesLibrary().getFunction<PROC_ES2_glCullFace>("glCullFace");
	gl::DeleteBuffers = glesLibrary().getFunction<PROC_ES2_glDeleteBuffers>("glDeleteBuffers");
	gl::DeleteFramebuffers = glesLibrary().getFunction<PROC_ES2_glDeleteFramebuffers>("glDeleteFramebuffers");
	gl::DeleteTextures = glesLibrary().getFunction<PROC_ES2_glDeleteTextures>("glDeleteTextures");
	gl::DeleteProgram = glesLibrary().getFunction<PROC_ES2_glDeleteProgram>("glDeleteProgram");
	gl::DeleteRenderbuffers = glesLibrary().getFunction<PROC_ES2_glDeleteRenderbuffers>("glDeleteRenderbuffers");
	gl::DeleteShader = glesLibrary().getFunction<PROC_ES2_glDeleteShader>("glDeleteShader");
	gl::DetachShader = glesLibrary().getFunction<PROC_ES2_glDetachShader>("glDetachShader");
	gl::DepthFunc = glesLibrary().getFunction<PROC_ES2_glDepthFunc>("glDepthFunc");
	gl::DepthMask = glesLibrary().getFunction<PROC_ES2_glDepthMask>("glDepthMask");
	gl::DepthRangef = glesLibrary().getFunction<PROC_ES2_glDepthRangef>("glDepthRangef");
	gl::Disable = glesLibrary().getFunction<PROC_ES2_glDisable>("glDisable");
	gl::DisableVertexAttribArray =  glesLibrary().getFunction<PROC_ES2_glDisableVertexAttribArray>("glDisableVertexAttribArray");
	gl::DrawArrays = glesLibrary().getFunction<PROC_ES2_glDrawArrays>("glDrawArrays");
	gl::DrawElements = glesLibrary().getFunction<PROC_ES2_glDrawElements>("glDrawElements");
	gl::Enable = glesLibrary().getFunction<PROC_ES2_glEnable>("glEnable");
	gl::EnableVertexAttribArray = glesLibrary().getFunction<PROC_ES2_glEnableVertexAttribArray>("glEnableVertexAttribArray");
	gl::Finish = glesLibrary().getFunction<PROC_ES2_glFinish>("glFinish");
	gl::Flush = glesLibrary().getFunction<PROC_ES2_glFlush>("glFlush");
	gl::FramebufferRenderbuffer = glesLibrary().getFunction<PROC_ES2_glFramebufferRenderbuffer>("glFramebufferRenderbuffer");
	gl::FramebufferTexture2D = glesLibrary().getFunction<PROC_ES2_glFramebufferTexture2D>("glFramebufferTexture2D");
	gl::FrontFace = glesLibrary().getFunction<PROC_ES2_glFrontFace>("glFrontFace");
	gl::GenBuffers = glesLibrary().getFunction<PROC_ES2_glGenBuffers>("glGenBuffers");
	gl::GenerateMipmap = glesLibrary().getFunction<PROC_ES2_glGenerateMipmap>("glGenerateMipmap");
	gl::GenFramebuffers = glesLibrary().getFunction<PROC_ES2_glGenFramebuffers>("glGenFramebuffers");
	gl::GenRenderbuffers = glesLibrary().getFunction<PROC_ES2_glGenRenderbuffers>("glGenRenderbuffers");
	gl::GenTextures = glesLibrary().getFunction<PROC_ES2_glGenTextures>("glGenTextures");
	gl::GetActiveAttrib = glesLibrary().getFunction<PROC_ES2_glGetActiveAttrib>("glGetActiveAttrib");
	gl::GetActiveUniform = glesLibrary().getFunction<PROC_ES2_glGetActiveUniform>("glGetActiveUniform");
	gl::GetAttachedShaders = glesLibrary().getFunction<PROC_ES2_glGetAttachedShaders>("glGetAttachedShaders");
	gl::GetAttribLocation = glesLibrary().getFunction<PROC_ES2_glGetAttribLocation>("glGetAttribLocation");
	gl::GetBooleanv = glesLibrary().getFunction<PROC_ES2_glGetBooleanv>("glGetBooleanv");
	gl::GetBufferParameteriv = glesLibrary().getFunction<PROC_ES2_glGetBufferParameteriv>("glGetBufferParameteriv");
	gl::GetError = glesLibrary().getFunction<PROC_ES2_glGetError>("glGetError");
	gl::GetFloatv = glesLibrary().getFunction<PROC_ES2_glGetFloatv>("glGetFloatv");
	gl::GetFramebufferAttachmentParameteriv =
	  glesLibrary().getFunction<PROC_ES2_glGetFramebufferAttachmentParameteriv>("glGetFramebufferAttachmentParameteriv");
	gl::GetIntegerv = glesLibrary().getFunction<PROC_ES2_glGetIntegerv>("glGetIntegerv");
	gl::GetProgramiv = glesLibrary().getFunction<PROC_ES2_glGetProgramiv>("glGetProgramiv");
	gl::GetProgramInfoLog = glesLibrary().getFunction<PROC_ES2_glGetProgramInfoLog>("glGetProgramInfoLog");
	gl::GetRenderbufferParameteriv = glesLibrary().getFunction<PROC_ES2_glGetRenderbufferParameteriv>("glGetRenderbufferParameteriv");
	gl::GetShaderiv = glesLibrary().getFunction<PROC_ES2_glGetShaderiv>("glGetShaderiv");
	gl::GetShaderInfoLog = glesLibrary().getFunction<PROC_ES2_glGetShaderInfoLog>("glGetShaderInfoLog");
	gl::GetShaderPrecisionFormat = glesLibrary().getFunction<PROC_ES2_glGetShaderPrecisionFormat>("glGetShaderPrecisionFormat");
	gl::GetShaderSource = glesLibrary().getFunction<PROC_ES2_glGetShaderSource>("glGetShaderSource");
	gl::GetString = glesLibrary().getFunction<PROC_ES2_glGetString>("glGetString");
	gl::GetTexParameterfv = glesLibrary().getFunction<PROC_ES2_glGetTexParameterfv>("glGetTexParameterfv");
	gl::GetTexParameteriv = glesLibrary().getFunction<PROC_ES2_glGetTexParameteriv>("glGetTexParameteriv");
	gl::GetUniformfv = glesLibrary().getFunction<PROC_ES2_glGetUniformfv>("glGetUniformfv");
	gl::GetUniformiv = glesLibrary().getFunction<PROC_ES2_glGetUniformiv>("glGetUniformiv");
	gl::GetUniformLocation = glesLibrary().getFunction<PROC_ES2_glGetUniformLocation>("glGetUniformLocation");
	gl::GetVertexAttribfv = glesLibrary().getFunction<PROC_ES2_glGetVertexAttribfv>("glGetVertexAttribfv");
	gl::GetVertexAttribiv = glesLibrary().getFunction<PROC_ES2_glGetVertexAttribiv>("glGetVertexAttribiv");
	gl::GetVertexAttribPointerv = glesLibrary().getFunction<PROC_ES2_glGetVertexAttribPointerv>("glGetVertexAttribPointerv");
	gl::Hint = glesLibrary().getFunction<PROC_ES2_glHint>("glHint");
	gl::IsBuffer = glesLibrary().getFunction<PROC_ES2_glIsBuffer>("glIsBuffer");
	gl::IsEnabled = glesLibrary().getFunction<PROC_ES2_glIsEnabled>("glIsEnabled");
	gl::IsFramebuffer = glesLibrary().getFunction<PROC_ES2_glIsFramebuffer>("glIsFramebuffer");
	gl::IsProgram = glesLibrary().getFunction<PROC_ES2_glIsProgram>("glIsProgram");
	gl::IsRenderbuffer = glesLibrary().getFunction<PROC_ES2_glIsRenderbuffer>("glIsRenderbuffer");
	gl::IsShader = glesLibrary().getFunction<PROC_ES2_glIsShader>("glIsShader");
	gl::IsTexture = glesLibrary().getFunction<PROC_ES2_glIsTexture>("glIsTexture");
	gl::LineWidth = glesLibrary().getFunction<PROC_ES2_glLineWidth>("glLineWidth");
	gl::LinkProgram = glesLibrary().getFunction<PROC_ES2_glLinkProgram>("glLinkProgram");
	gl::PixelStorei = glesLibrary().getFunction<PROC_ES2_glPixelStorei>("glPixelStorei");
	gl::PolygonOffset = glesLibrary().getFunction<PROC_ES2_glPolygonOffset>("glPolygonOffset");
	gl::ReadPixels = glesLibrary().getFunction<PROC_ES2_glReadPixels>("glReadPixels");
	gl::ReleaseShaderCompiler = glesLibrary().getFunction<PROC_ES2_glReleaseShaderCompiler>("glReleaseShaderCompiler");
	gl::RenderbufferStorage = glesLibrary().getFunction<PROC_ES2_glRenderbufferStorage>("glRenderbufferStorage");
	gl::SampleCoverage = glesLibrary().getFunction<PROC_ES2_glSampleCoverage>("glSampleCoverage");
	gl::Scissor = glesLibrary().getFunction<PROC_ES2_glScissor>("glScissor");
	gl::ShaderBinary = glesLibrary().getFunction<PROC_ES2_glShaderBinary>("glShaderBinary");
	gl::ShaderSource = glesLibrary().getFunction<PROC_ES2_glShaderSource>("glShaderSource");
	gl::StencilFunc = glesLibrary().getFunction<PROC_ES2_glStencilFunc>("glStencilFunc");
	gl::StencilFuncSeparate = glesLibrary().getFunction<PROC_ES2_glStencilFuncSeparate>("glStencilFuncSeparate");
	gl::StencilMask = glesLibrary().getFunction<PROC_ES2_glStencilMask>("glStencilMask");
	gl::StencilMaskSeparate = glesLibrary().getFunction<PROC_ES2_glStencilMaskSeparate>("glStencilMaskSeparate");
	gl::StencilOp = glesLibrary().getFunction<PROC_ES2_glStencilOp>("glStencilOp");
	gl::StencilOpSeparate = glesLibrary().getFunction<PROC_ES2_glStencilOpSeparate>("glStencilOpSeparate");
	gl::TexImage2D = glesLibrary().getFunction<PROC_ES2_glTexImage2D>("glTexImage2D");
	gl::TexParameterf = glesLibrary().getFunction<PROC_ES2_glTexParameterf>("glTexParameterf");
	gl::TexParameterfv = glesLibrary().getFunction<PROC_ES2_glTexParameterfv>("glTexParameterfv");
	gl::TexParameteri = glesLibrary().getFunction<PROC_ES2_glTexParameteri>("glTexParameteri");
	gl::TexParameteriv = glesLibrary().getFunction<PROC_ES2_glTexParameteriv>("glTexParameteriv");
	gl::TexSubImage2D = glesLibrary().getFunction<PROC_ES2_glTexSubImage2D>("glTexSubImage2D");
	gl::Uniform1f = glesLibrary().getFunction<PROC_ES2_glUniform1f>("glUniform1f");
	gl::Uniform1fv = glesLibrary().getFunction<PROC_ES2_glUniform1fv>("glUniform1fv");
	gl::Uniform1i = glesLibrary().getFunction<PROC_ES2_glUniform1i>("glUniform1i");
	gl::Uniform1iv = glesLibrary().getFunction<PROC_ES2_glUniform1iv>("glUniform1iv");
	gl::Uniform2f = glesLibrary().getFunction<PROC_ES2_glUniform2f>("glUniform2f");
	gl::Uniform2fv = glesLibrary().getFunction<PROC_ES2_glUniform2fv>("glUniform2fv");
	gl::Uniform2i = glesLibrary().getFunction<PROC_ES2_glUniform2i>("glUniform2i");
	gl::Uniform2iv = glesLibrary().getFunction<PROC_ES2_glUniform2iv>("glUniform2iv");
	gl::Uniform3f = glesLibrary().getFunction<PROC_ES2_glUniform3f>("glUniform3f");
	gl::Uniform3fv = glesLibrary().getFunction<PROC_ES2_glUniform3fv>("glUniform3fv");
	gl::Uniform3i = glesLibrary().getFunction<PROC_ES2_glUniform3i>("glUniform3i");
	gl::Uniform3iv = glesLibrary().getFunction<PROC_ES2_glUniform3iv>("glUniform3iv");
	gl::Uniform4f = glesLibrary().getFunction<PROC_ES2_glUniform4f>("glUniform4f");
	gl::Uniform4fv = glesLibrary().getFunction<PROC_ES2_glUniform4fv>("glUniform4fv");
	gl::Uniform4i = glesLibrary().getFunction<PROC_ES2_glUniform4i>("glUniform4i");
	gl::Uniform4iv = glesLibrary().getFunction<PROC_ES2_glUniform4iv>("glUniform4iv");
	gl::UniformMatrix2fv = glesLibrary().getFunction<PROC_ES2_glUniformMatrix2fv>("glUniformMatrix2fv");
	gl::UniformMatrix3fv = glesLibrary().getFunction<PROC_ES2_glUniformMatrix3fv>("glUniformMatrix3fv");
	gl::UniformMatrix4fv = glesLibrary().getFunction<PROC_ES2_glUniformMatrix4fv>("glUniformMatrix4fv");
	gl::UseProgram = glesLibrary().getFunction<PROC_ES2_glUseProgram>("glUseProgram");
	gl::ValidateProgram = glesLibrary().getFunction<PROC_ES2_glValidateProgram>("glValidateProgram");
	gl::VertexAttrib1f = glesLibrary().getFunction<PROC_ES2_glVertexAttrib1f>("glVertexAttrib1f");
	gl::VertexAttrib1fv = glesLibrary().getFunction<PROC_ES2_glVertexAttrib1fv>("glVertexAttrib1fv");
	gl::VertexAttrib2f = glesLibrary().getFunction<PROC_ES2_glVertexAttrib2f>("glVertexAttrib2f");
	gl::VertexAttrib2fv = glesLibrary().getFunction<PROC_ES2_glVertexAttrib2fv>("glVertexAttrib2fv");
	gl::VertexAttrib3f = glesLibrary().getFunction<PROC_ES2_glVertexAttrib3f>("glVertexAttrib3f");
	gl::VertexAttrib3fv = glesLibrary().getFunction<PROC_ES2_glVertexAttrib3fv>("glVertexAttrib3fv");
	gl::VertexAttrib4f = glesLibrary().getFunction<PROC_ES2_glVertexAttrib4f>("glVertexAttrib4f");
	gl::VertexAttrib4fv = glesLibrary().getFunction<PROC_ES2_glVertexAttrib4fv>("glVertexAttrib4fv");
	gl::VertexAttribPointer = glesLibrary().getFunction<PROC_ES2_glVertexAttribPointer>("glVertexAttribPointer");
	gl::Viewport = glesLibrary().getFunction<PROC_ES2_glViewport>("glViewport");

#if BUILD_API_MAX>=30
	// Now attempt to load ES3
	gl::ReadBuffer = glesLibrary().getFunction<PROC_ES3_glReadBuffer>("glReadBuffer");
	gl::DrawRangeElements = glesLibrary().getFunction<PROC_ES3_glDrawRangeElements>("glDrawRangeElements");
	gl::TexImage3D = glesLibrary().getFunction<PROC_ES3_glTexImage3D>("glTexImage3D");
	gl::TexSubImage3D = glesLibrary().getFunction<PROC_ES3_glTexSubImage3D>("glTexSubImage3D");
	gl::CopyTexSubImage3D = glesLibrary().getFunction<PROC_ES3_glCopyTexSubImage3D>("glCopyTexSubImage3D");
	gl::CompressedTexImage3D = glesLibrary().getFunction<PROC_ES3_glCompressedTexImage3D>("glCompressedTexImage3D");
	gl::CompressedTexSubImage3D = glesLibrary().getFunction<PROC_ES3_glCompressedTexSubImage3D>("glCompressedTexSubImage3D");
	gl::GenQueries = glesLibrary().getFunction<PROC_ES3_glGenQueries>("glGenQueries");
	gl::DeleteQueries = glesLibrary().getFunction<PROC_ES3_glDeleteQueries>("glDeleteQueries");
	gl::IsQuery = glesLibrary().getFunction<PROC_ES3_glIsQuery>("glIsQuery");
	gl::BeginQuery = glesLibrary().getFunction<PROC_ES3_glBeginQuery>("glBeginQuery");
	gl::EndQuery = glesLibrary().getFunction<PROC_ES3_glEndQuery>("glEndQuery");
	gl::GetQueryiv = glesLibrary().getFunction<PROC_ES3_glGetQueryiv>("glGetQueryiv");
	gl::GetQueryObjectuiv = glesLibrary().getFunction<PROC_ES3_glGetQueryObjectuiv>("glGetQueryObjectuiv");
	gl::UnmapBuffer = glesLibrary().getFunction<PROC_ES3_glUnmapBuffer>("glUnmapBuffer");
	gl::GetBufferPointerv = glesLibrary().getFunction<PROC_ES3_glGetBufferPointerv>("glGetBufferPointerv");
	gl::DrawBuffers = glesLibrary().getFunction<PROC_ES3_glDrawBuffers>("glDrawBuffers");
	gl::UniformMatrix2x3fv = glesLibrary().getFunction<PROC_ES3_glUniformMatrix2x3fv>("glUniformMatrix2x3fv");
	gl::UniformMatrix3x2fv = glesLibrary().getFunction<PROC_ES3_glUniformMatrix3x2fv>("glUniformMatrix3x2fv");
	gl::UniformMatrix2x4fv = glesLibrary().getFunction<PROC_ES3_glUniformMatrix2x4fv>("glUniformMatrix2x4fv");
	gl::UniformMatrix4x2fv = glesLibrary().getFunction<PROC_ES3_glUniformMatrix4x2fv>("glUniformMatrix4x2fv");
	gl::UniformMatrix3x4fv = glesLibrary().getFunction<PROC_ES3_glUniformMatrix3x4fv>("glUniformMatrix3x4fv");
	gl::UniformMatrix4x3fv = glesLibrary().getFunction<PROC_ES3_glUniformMatrix4x3fv>("glUniformMatrix4x3fv");
	gl::BlitFramebuffer = glesLibrary().getFunction<PROC_ES3_glBlitFramebuffer>("glBlitFramebuffer");
	gl::RenderbufferStorageMultisample =
	  glesLibrary().getFunction<PROC_ES3_glRenderbufferStorageMultisample>("glRenderbufferStorageMultisample");
	gl::FramebufferTextureLayer = glesLibrary().getFunction<PROC_ES3_glFramebufferTextureLayer>("glFramebufferTextureLayer");
	gl::MapBufferRange = glesLibrary().getFunction<PROC_ES3_glMapBufferRange>("glMapBufferRange");
	gl::FlushMappedBufferRange = glesLibrary().getFunction<PROC_ES3_glFlushMappedBufferRange>("glFlushMappedBufferRange");
	gl::BindVertexArray = glesLibrary().getFunction<PROC_ES3_glBindVertexArray>("glBindVertexArray");
	gl::DeleteVertexArrays = glesLibrary().getFunction<PROC_ES3_glDeleteVertexArrays>("glDeleteVertexArrays");
	gl::GenVertexArrays = glesLibrary().getFunction<PROC_ES3_glGenVertexArrays>("glGenVertexArrays");
	gl::IsVertexArray = glesLibrary().getFunction<PROC_ES3_glIsVertexArray>("glIsVertexArray");
	gl::GetIntegeri_v = glesLibrary().getFunction<PROC_ES3_glGetIntegeri_v>("glGetIntegeri_v");
	gl::BeginTransformFeedback = glesLibrary().getFunction<PROC_ES3_glBeginTransformFeedback>("glBeginTransformFeedback");
	gl::EndTransformFeedback = glesLibrary().getFunction<PROC_ES3_glEndTransformFeedback>("glEndTransformFeedback");
	gl::BindBufferRange = glesLibrary().getFunction<PROC_ES3_glBindBufferRange>("glBindBufferRange");
	gl::BindBufferBase = glesLibrary().getFunction<PROC_ES3_glBindBufferBase>("glBindBufferBase");
	gl::TransformFeedbackVaryings = glesLibrary().getFunction<PROC_ES3_glTransformFeedbackVaryings>("glTransformFeedbackVaryings");
	gl::GetTransformFeedbackVarying =
	  glesLibrary().getFunction<PROC_ES3_glGetTransformFeedbackVarying>("glGetTransformFeedbackVarying");
	gl::VertexAttribIPointer = glesLibrary().getFunction<PROC_ES3_glVertexAttribIPointer>("glVertexAttribIPointer");
	gl::GetVertexAttribIiv = glesLibrary().getFunction<PROC_ES3_glGetVertexAttribIiv>("glGetVertexAttribIiv");
	gl::GetVertexAttribIuiv = glesLibrary().getFunction<PROC_ES3_glGetVertexAttribIuiv>("glGetVertexAttribIuiv");
	gl::VertexAttribI4i = glesLibrary().getFunction<PROC_ES3_glVertexAttribI4i>("glVertexAttribI4i");
	gl::VertexAttribI4ui = glesLibrary().getFunction<PROC_ES3_glVertexAttribI4ui>("glVertexAttribI4ui");
	gl::VertexAttribI4iv = glesLibrary().getFunction<PROC_ES3_glVertexAttribI4iv>("glVertexAttribI4iv");
	gl::VertexAttribI4uiv = glesLibrary().getFunction<PROC_ES3_glVertexAttribI4uiv>("glVertexAttribI4uiv");
	gl::GetUniformuiv = glesLibrary().getFunction<PROC_ES3_glGetUniformuiv>("glGetUniformuiv");
	gl::GetFragDataLocation = glesLibrary().getFunction<PROC_ES3_glGetFragDataLocation>("glGetFragDataLocation");
	gl::Uniform1ui = glesLibrary().getFunction<PROC_ES3_glUniform1ui>("glUniform1ui");
	gl::Uniform2ui = glesLibrary().getFunction<PROC_ES3_glUniform2ui>("glUniform2ui");
	gl::Uniform3ui = glesLibrary().getFunction<PROC_ES3_glUniform3ui>("glUniform3ui");
	gl::Uniform4ui = glesLibrary().getFunction<PROC_ES3_glUniform4ui>("glUniform4ui");
	gl::Uniform1uiv = glesLibrary().getFunction<PROC_ES3_glUniform1uiv>("glUniform1uiv");
	gl::Uniform2uiv = glesLibrary().getFunction<PROC_ES3_glUniform2uiv>("glUniform2uiv");
	gl::Uniform3uiv = glesLibrary().getFunction<PROC_ES3_glUniform3uiv>("glUniform3uiv");
	gl::Uniform4uiv = glesLibrary().getFunction<PROC_ES3_glUniform4uiv>("glUniform4uiv");
	gl::ClearBufferiv = glesLibrary().getFunction<PROC_ES3_glClearBufferiv>("glClearBufferiv");
	gl::ClearBufferuiv = glesLibrary().getFunction<PROC_ES3_glClearBufferuiv>("glClearBufferuiv");
	gl::ClearBufferfv = glesLibrary().getFunction<PROC_ES3_glClearBufferfv>("glClearBufferfv");
	gl::ClearBufferfi = glesLibrary().getFunction<PROC_ES3_glClearBufferfi>("glClearBufferfi");
	gl::GetStringi = glesLibrary().getFunction<PROC_ES3_glGetStringi>("glGetStringi");
	gl::CopyBufferSubData = glesLibrary().getFunction<PROC_ES3_glCopyBufferSubData>("glCopyBufferSubData");
	gl::GetUniformIndices = glesLibrary().getFunction<PROC_ES3_glGetUniformIndices>("glGetUniformIndices");
	gl::GetActiveUniformsiv = glesLibrary().getFunction<PROC_ES3_glGetActiveUniformsiv>("glGetActiveUniformsiv");
	gl::GetUniformBlockIndex = glesLibrary().getFunction<PROC_ES3_glGetUniformBlockIndex>("glGetUniformBlockIndex");
	gl::GetActiveUniformBlockiv = glesLibrary().getFunction<PROC_ES3_glGetActiveUniformBlockiv>("glGetActiveUniformBlockiv");
	gl::GetActiveUniformBlockName = glesLibrary().getFunction<PROC_ES3_glGetActiveUniformBlockName>("glGetActiveUniformBlockName");
	gl::UniformBlockBinding = glesLibrary().getFunction<PROC_ES3_glUniformBlockBinding>("glUniformBlockBinding");
	gl::DrawArraysInstanced = glesLibrary().getFunction<PROC_ES3_glDrawArraysInstanced>("glDrawArraysInstanced");
	gl::DrawElementsInstanced = glesLibrary().getFunction<PROC_ES3_glDrawElementsInstanced>("glDrawElementsInstanced");
	gl::FenceSync = glesLibrary().getFunction<PROC_ES3_glFenceSync>("glFenceSync");
	gl::IsSync = glesLibrary().getFunction<PROC_ES3_glIsSync>("glIsSync");
	gl::DeleteSync = glesLibrary().getFunction<PROC_ES3_glDeleteSync>("glDeleteSync");
	gl::ClientWaitSync = glesLibrary().getFunction<PROC_ES3_glClientWaitSync>("glClientWaitSync");
	gl::WaitSync = glesLibrary().getFunction<PROC_ES3_glWaitSync>("glWaitSync");
	gl::GetInteger64v = glesLibrary().getFunction<PROC_ES3_glGetInteger64v>("glGetInteger64v");
	gl::GetSynciv = glesLibrary().getFunction<PROC_ES3_glGetSynciv>("glGetSynciv");
	gl::GetInteger64i_v = glesLibrary().getFunction<PROC_ES3_glGetInteger64i_v>("glGetInteger64i_v");
	gl::GetBufferParameteri64v = glesLibrary().getFunction<PROC_ES3_glGetBufferParameteri64v>("glGetBufferParameteri64v");
	gl::GenSamplers = glesLibrary().getFunction<PROC_ES3_glGenSamplers>("glGenSamplers");
	gl::DeleteSamplers = glesLibrary().getFunction<PROC_ES3_glDeleteSamplers>("glDeleteSamplers");
	gl::IsSampler = glesLibrary().getFunction<PROC_ES3_glIsSampler>("glIsSampler");
	gl::BindSampler = glesLibrary().getFunction<PROC_ES3_glBindSampler>("glBindSampler");
	gl::SamplerParameteri = glesLibrary().getFunction<PROC_ES3_glSamplerParameteri>("glSamplerParameteri");
	gl::SamplerParameteriv = glesLibrary().getFunction<PROC_ES3_glSamplerParameteriv>("glSamplerParameteriv");
	gl::SamplerParameterf = glesLibrary().getFunction<PROC_ES3_glSamplerParameterf>("glSamplerParameterf");
	gl::SamplerParameterfv = glesLibrary().getFunction<PROC_ES3_glSamplerParameterfv>("glSamplerParameterfv");
	gl::GetSamplerParameteriv = glesLibrary().getFunction<PROC_ES3_glGetSamplerParameteriv>("glGetSamplerParameteriv");
	gl::GetSamplerParameterfv = glesLibrary().getFunction<PROC_ES3_glGetSamplerParameterfv>("glGetSamplerParameterfv");
	gl::VertexAttribDivisor = glesLibrary().getFunction<PROC_ES3_glVertexAttribDivisor>("glVertexAttribDivisor");
	gl::BindTransformFeedback = glesLibrary().getFunction<PROC_ES3_glBindTransformFeedback>("glBindTransformFeedback");
	gl::DeleteTransformFeedbacks = glesLibrary().getFunction<PROC_ES3_glDeleteTransformFeedbacks>("glDeleteTransformFeedbacks");
	gl::GenTransformFeedbacks = glesLibrary().getFunction<PROC_ES3_glGenTransformFeedbacks>("glGenTransformFeedbacks");
	gl::IsTransformFeedback = glesLibrary().getFunction<PROC_ES3_glIsTransformFeedback>("glIsTransformFeedback");
	gl::PauseTransformFeedback = glesLibrary().getFunction<PROC_ES3_glPauseTransformFeedback>("glPauseTransformFeedback");
	gl::ResumeTransformFeedback = glesLibrary().getFunction<PROC_ES3_glResumeTransformFeedback>("glResumeTransformFeedback");
	gl::GetProgramBinary = glesLibrary().getFunction<PROC_ES3_glGetProgramBinary>("glGetProgramBinary");
	gl::ProgramBinary = glesLibrary().getFunction<PROC_ES3_glProgramBinary>("glProgramBinary");
	gl::ProgramParameteri = glesLibrary().getFunction<PROC_ES3_glProgramParameteri>("glProgramParameteri");
	gl::InvalidateFramebuffer = glesLibrary().getFunction<PROC_ES3_glInvalidateFramebuffer>("glInvalidateFramebuffer");
	gl::InvalidateSubFramebuffer = glesLibrary().getFunction<PROC_ES3_glInvalidateSubFramebuffer>("glInvalidateSubFramebuffer");
	gl::TexStorage2D = glesLibrary().getFunction<PROC_ES3_glTexStorage2D>("glTexStorage2D");
	gl::TexStorage3D = glesLibrary().getFunction<PROC_ES3_glTexStorage3D>("glTexStorage3D");
	gl::GetInternalformativ = glesLibrary().getFunction<PROC_ES3_glGetInternalformativ>("glGetInternalformativ");
#endif

#if BUILD_API_MAX>=31
	// Now attempt to load ES3.1
	gl::DispatchCompute = (PROC_ES31_glDispatchCompute)glesLibrary().getFunction("glDispatchCompute");
	gl::DispatchComputeIndirect = (PROC_ES31_glDispatchComputeIndirect)glesLibrary().getFunction("glDispatchComputeIndirect");
	gl::BindImageTexture = (PROC_ES31_glBindImageTexture)glesLibrary().getFunction("glBindImageTexture");
	gl::MemoryBarrier = (PROC_ES31_glMemoryBarrier)glesLibrary().getFunction("glMemoryBarrier");
	gl::MemoryBarrierByRegion = (PROC_ES31_glMemoryBarrierByRegion)glesLibrary().getFunction("glMemoryBarrierByRegion");
	gl::BindProgramPipeline = (PROC_ES31_glBindProgramPipeline)glesLibrary().getFunction("glBindProgramPipeline");
	gl::DeleteProgramPipelines = (PROC_ES31_glDeleteProgramPipelines)glesLibrary().getFunction("glDeleteProgramPipelines");
	gl::GenProgramPipelines = (PROC_ES31_glGenProgramPipelines)glesLibrary().getFunction("glGenProgramPipelines");
	gl::IsProgramPipeline = (PROC_ES31_glIsProgramPipeline)glesLibrary().getFunction("glIsProgramPipeline");
	gl::GetProgramPipelineiv = (PROC_ES31_glGetProgramPipelineiv)glesLibrary().getFunction("glGetProgramPipelineiv");
	gl::ValidateProgramPipeline = (PROC_ES31_glValidateProgramPipeline)glesLibrary().getFunction("glValidateProgramPipeline");
	gl::GetProgramPipelineInfoLog = (PROC_ES31_glGetProgramPipelineInfoLog)glesLibrary().getFunction("glGetProgramPipelineInfoLog");
	gl::UseProgramStages = (PROC_ES31_glUseProgramStages)glesLibrary().getFunction("glUseProgramStages");
	gl::ActiveShaderProgram = (PROC_ES31_glActiveShaderProgram)glesLibrary().getFunction("glActiveShaderProgram");
	gl::ProgramUniform1i = (PROC_ES31_glProgramUniform1i)glesLibrary().getFunction("glProgramUniform1i");
	gl::ProgramUniform2i = (PROC_ES31_glProgramUniform2i)glesLibrary().getFunction("glProgramUniform2i");
	gl::ProgramUniform3i = (PROC_ES31_glProgramUniform3i)glesLibrary().getFunction("glProgramUniform3i");
	gl::ProgramUniform4i = (PROC_ES31_glProgramUniform4i)glesLibrary().getFunction("glProgramUniform4i");
	gl::ProgramUniform1ui = (PROC_ES31_glProgramUniform1ui)glesLibrary().getFunction("glProgramUniform1ui");
	gl::ProgramUniform2ui = (PROC_ES31_glProgramUniform2ui)glesLibrary().getFunction("glProgramUniform2ui");
	gl::ProgramUniform3ui = (PROC_ES31_glProgramUniform3ui)glesLibrary().getFunction("glProgramUniform3ui");
	gl::ProgramUniform4ui = (PROC_ES31_glProgramUniform4ui)glesLibrary().getFunction("glProgramUniform4ui");
	gl::ProgramUniform1f = (PROC_ES31_glProgramUniform1f)glesLibrary().getFunction("glProgramUniform1f");
	gl::ProgramUniform2f = (PROC_ES31_glProgramUniform2f)glesLibrary().getFunction("glProgramUniform2f");
	gl::ProgramUniform3f = (PROC_ES31_glProgramUniform3f)glesLibrary().getFunction("glProgramUniform3f");
	gl::ProgramUniform4f = (PROC_ES31_glProgramUniform4f)glesLibrary().getFunction("glProgramUniform4f");
	gl::ProgramUniform1iv = (PROC_ES31_glProgramUniform1iv)glesLibrary().getFunction("glProgramUniform1iv");
	gl::ProgramUniform2iv = (PROC_ES31_glProgramUniform2iv)glesLibrary().getFunction("glProgramUniform2iv");
	gl::ProgramUniform3iv = (PROC_ES31_glProgramUniform3iv)glesLibrary().getFunction("glProgramUniform3iv");
	gl::ProgramUniform4iv = (PROC_ES31_glProgramUniform4iv)glesLibrary().getFunction("glProgramUniform4iv");
	gl::ProgramUniform1uiv = (PROC_ES31_glProgramUniform1uiv)glesLibrary().getFunction("glProgramUniform1uiv");
	gl::ProgramUniform2uiv = (PROC_ES31_glProgramUniform2uiv)glesLibrary().getFunction("glProgramUniform2uiv");
	gl::ProgramUniform3uiv = (PROC_ES31_glProgramUniform3uiv)glesLibrary().getFunction("glProgramUniform3uiv");
	gl::ProgramUniform4uiv = (PROC_ES31_glProgramUniform4uiv)glesLibrary().getFunction("glProgramUniform4uiv");
	gl::ProgramUniform1fv = (PROC_ES31_glProgramUniform1fv)glesLibrary().getFunction("glProgramUniform1fv");
	gl::ProgramUniform2fv = (PROC_ES31_glProgramUniform2fv)glesLibrary().getFunction("glProgramUniform2fv");
	gl::ProgramUniform3fv = (PROC_ES31_glProgramUniform3fv)glesLibrary().getFunction("glProgramUniform3fv");
	gl::ProgramUniform4fv = (PROC_ES31_glProgramUniform4fv)glesLibrary().getFunction("glProgramUniform4fv");
	gl::ProgramUniformMatrix2fv = (PROC_ES31_glProgramUniformMatrix2fv)glesLibrary().getFunction("glProgramUniformMatrix2fv");
	gl::ProgramUniformMatrix3fv = (PROC_ES31_glProgramUniformMatrix3fv)glesLibrary().getFunction("glProgramUniformMatrix3fv");
	gl::ProgramUniformMatrix4fv = (PROC_ES31_glProgramUniformMatrix4fv)glesLibrary().getFunction("glProgramUniformMatrix4fv");
	gl::ProgramUniformMatrix2x3fv = (PROC_ES31_glProgramUniformMatrix2x3fv)glesLibrary().getFunction("glProgramUniformMatrix2x3fv");
	gl::ProgramUniformMatrix3x2fv = (PROC_ES31_glProgramUniformMatrix3x2fv)glesLibrary().getFunction("glProgramUniformMatrix3x2fv");
	gl::ProgramUniformMatrix2x4fv = (PROC_ES31_glProgramUniformMatrix2x4fv)glesLibrary().getFunction("glProgramUniformMatrix2x4fv");
	gl::ProgramUniformMatrix4x2fv = (PROC_ES31_glProgramUniformMatrix4x2fv)glesLibrary().getFunction("glProgramUniformMatrix4x2fv");
	gl::ProgramUniformMatrix3x4fv = (PROC_ES31_glProgramUniformMatrix3x4fv)glesLibrary().getFunction("glProgramUniformMatrix3x4fv");
	gl::ProgramUniformMatrix4x3fv = (PROC_ES31_glProgramUniformMatrix4x3fv)glesLibrary().getFunction("glProgramUniformMatrix4x3fv");
	gl::CreateShaderProgramv = (PROC_ES31_glCreateShaderProgramv)glesLibrary().getFunction("glCreateShaderProgramv");
	gl::DrawArraysIndirect = (PROC_ES31_glDrawArraysIndirect)glesLibrary().getFunction("glDrawArraysIndirect");
	gl::DrawElementsIndirect = (PROC_ES31_glDrawElementsIndirect)glesLibrary().getFunction("glDrawElementsIndirect");
	gl::TexStorage2DMultisample = (PROC_ES31_glTexStorage2DMultisample)glesLibrary().getFunction("glTexStorage2DMultisample");
	gl::SampleMaski = (PROC_ES31_glSampleMaski)glesLibrary().getFunction("glSampleMaski");
	gl::BindVertexBuffer = (PROC_ES31_glBindVertexBuffer)glesLibrary().getFunction("glBindVertexBuffer");
	gl::VertexAttribFormat = (PROC_ES31_glVertexAttribFormat)glesLibrary().getFunction("glVertexAttribFormat");
	gl::VertexAttribIFormat = (PROC_ES31_glVertexAttribIFormat)glesLibrary().getFunction("glVertexAttribIFormat");
	gl::VertexAttribBinding = (PROC_ES31_glVertexAttribBinding)glesLibrary().getFunction("glVertexAttribBinding");
	gl::VertexBindingDivisor = (PROC_ES31_glVertexBindingDivisor)glesLibrary().getFunction("glVertexBindingDivisor");
	gl::FramebufferParameteri = (PROC_ES31_glFramebufferParameteri)glesLibrary().getFunction("glFramebufferParameteri");
	gl::GetFramebufferParameteriv = (PROC_ES31_glGetFramebufferParameteriv)glesLibrary().getFunction("glGetFramebufferParameteriv");
	gl::GetProgramInterfaceiv = (PROC_ES31_glGetProgramInterfaceiv)glesLibrary().getFunction("glGetProgramInterfaceiv");
	gl::GetProgramResourceIndex = (PROC_ES31_glGetProgramResourceIndex)glesLibrary().getFunction("glGetProgramResourceIndex");
	gl::GetProgramResourceName = (PROC_ES31_glGetProgramResourceName)glesLibrary().getFunction("glGetProgramResourceName");
	gl::GetProgramResourceiv = (PROC_ES31_glGetProgramResourceiv)glesLibrary().getFunction("glGetProgramResourceiv");
	gl::GetProgramResourceLocation = (PROC_ES31_glGetProgramResourceLocation)
	                                 glesLibrary().getFunction("glGetProgramResourceLocation");
	gl::GetBooleani_v = (PROC_ES31_glGetBooleani_v)glesLibrary().getFunction("glGetBooleani_v");
	gl::GetMultisamplefv = (PROC_ES31_glGetMultisamplefv)glesLibrary().getFunction("glGetMultisamplefv");
	gl::GetTexLevelParameteriv = (PROC_ES31_glGetTexLevelParameteriv)glesLibrary().getFunction("glGetTexLevelParameteriv");
	gl::GetTexLevelParameterfv = (PROC_ES31_glGetTexLevelParameterfv)glesLibrary().getFunction("glGetTexLevelParameterfv");
#endif

#else //TARGET_OS_IPHONE
// Load ES2 functionality
	gl::ActiveTexture = &glActiveTexture;
	gl::AttachShader = &glAttachShader;
	gl::BindAttribLocation = &glBindAttribLocation;
	gl::BindBuffer = &glBindBuffer;
	gl::BindFramebuffer = &glBindFramebuffer;
	gl::BindRenderbuffer = &glBindRenderbuffer;
	gl::BindTexture = &glBindTexture;
	gl::BlendColor = &glBlendColor;
	gl::BlendEquation = &glBlendEquation;
	gl::BlendEquationSeparate = &glBlendEquationSeparate;
	gl::BlendFunc = &glBlendFunc;
	gl::BlendFuncSeparate = &glBlendFuncSeparate;
	gl::BufferData = &glBufferData;
	gl::BufferSubData = &glBufferSubData;
	gl::CheckFramebufferStatus = &glCheckFramebufferStatus;
	gl::Clear = &glClear;
	gl::ClearColor = &glClearColor;
	gl::ClearDepthf = &glClearDepthf;
	gl::ClearStencil = &glClearStencil;
	gl::ColorMask = &glColorMask;
	gl::CompileShader = &glCompileShader;
	gl::CompressedTexImage2D = &glCompressedTexImage2D;
	gl::CompressedTexSubImage2D = &glCompressedTexSubImage2D;
	gl::CopyTexImage2D = &glCopyTexImage2D;
	gl::CopyTexSubImage2D = &glCopyTexSubImage2D;
	gl::CreateProgram = &glCreateProgram;
	gl::CreateShader = &glCreateShader;
	gl::CullFace = &glCullFace;
	gl::DeleteBuffers = &glDeleteBuffers;
	gl::DeleteFramebuffers = &glDeleteFramebuffers;
	gl::DeleteTextures = &glDeleteTextures;
	gl::DeleteProgram = &glDeleteProgram;
	gl::DeleteRenderbuffers = &glDeleteRenderbuffers;
	gl::DeleteShader = &glDeleteShader;
	gl::DetachShader = &glDetachShader;
	gl::DepthFunc = &glDepthFunc;
	gl::DepthMask = &glDepthMask;
	gl::DepthRangef = &glDepthRangef;
	gl::Disable = &glDisable;
	gl::DisableVertexAttribArray = &glDisableVertexAttribArray;
	gl::DrawArrays = &glDrawArrays;
	gl::DrawElements = &glDrawElements;
	gl::Enable = &glEnable;
	gl::EnableVertexAttribArray = &glEnableVertexAttribArray;
	gl::Finish = &glFinish;
	gl::Flush = &glFlush;
	gl::FramebufferRenderbuffer = &glFramebufferRenderbuffer;
	gl::FramebufferTexture2D = &glFramebufferTexture2D;
	gl::FrontFace = &glFrontFace;
	gl::GenBuffers = &glGenBuffers;
	gl::GenerateMipmap = &glGenerateMipmap;
	gl::GenFramebuffers = &glGenFramebuffers;
	gl::GenRenderbuffers = &glGenRenderbuffers;
	gl::GenTextures = &glGenTextures;
	gl::GetActiveAttrib = &glGetActiveAttrib;
	gl::GetActiveUniform = &glGetActiveUniform;
	gl::GetAttachedShaders = &glGetAttachedShaders;
	gl::GetAttribLocation = &glGetAttribLocation;
	gl::GetBooleanv = &glGetBooleanv;
	gl::GetBufferParameteriv = &glGetBufferParameteriv;
	gl::GetError = &glGetError;
	gl::GetFloatv = &glGetFloatv;
	gl::GetFramebufferAttachmentParameteriv = &glGetFramebufferAttachmentParameteriv;
	gl::GetIntegerv = &glGetIntegerv;
	gl::GetProgramiv = &glGetProgramiv;
	gl::GetProgramInfoLog = &glGetProgramInfoLog;
	gl::GetRenderbufferParameteriv = &glGetRenderbufferParameteriv;
	gl::GetShaderiv = &glGetShaderiv;
	gl::GetShaderInfoLog = &glGetShaderInfoLog;
	gl::GetShaderPrecisionFormat = &glGetShaderPrecisionFormat;
	gl::GetShaderSource = &glGetShaderSource;
	gl::GetString = &glGetString;
	gl::GetTexParameterfv = &glGetTexParameterfv;
	gl::GetTexParameteriv = &glGetTexParameteriv;
	gl::GetUniformfv = &glGetUniformfv;
	gl::GetUniformiv = &glGetUniformiv;
	gl::GetUniformLocation = &glGetUniformLocation;
	gl::GetVertexAttribfv = &glGetVertexAttribfv;
	gl::GetVertexAttribiv = &glGetVertexAttribiv;
	gl::GetVertexAttribPointerv = &glGetVertexAttribPointerv;
	gl::Hint = &glHint;
	gl::IsBuffer = &glIsBuffer;
	gl::IsEnabled = &glIsEnabled;
	gl::IsFramebuffer = &glIsFramebuffer;
	gl::IsProgram = &glIsProgram;
	gl::IsRenderbuffer = &glIsRenderbuffer;
	gl::IsShader = &glIsShader;
	gl::IsTexture = &glIsTexture;
	gl::LineWidth = &glLineWidth;
	gl::LinkProgram = &glLinkProgram;
	gl::PixelStorei = &glPixelStorei;
	gl::PolygonOffset = &glPolygonOffset;
	gl::ReadPixels = &glReadPixels;
	gl::ReleaseShaderCompiler = &glReleaseShaderCompiler;
	gl::RenderbufferStorage = &glRenderbufferStorage;
	gl::SampleCoverage = &glSampleCoverage;
	gl::Scissor = &glScissor;
	gl::ShaderBinary = &glShaderBinary;
	gl::ShaderSource = &glShaderSource;
	gl::StencilFunc = &glStencilFunc;
	gl::StencilFuncSeparate = &glStencilFuncSeparate;
	gl::StencilMask = &glStencilMask;
	gl::StencilMaskSeparate = &glStencilMaskSeparate;
	gl::StencilOp = &glStencilOp;
	gl::StencilOpSeparate = &glStencilOpSeparate;
	gl::TexImage2D = &glTexImage2D;
	gl::TexParameterf = &glTexParameterf;
	gl::TexParameterfv = &glTexParameterfv;
	gl::TexParameteri = &glTexParameteri;
	gl::TexParameteriv = &glTexParameteriv;
	gl::TexSubImage2D = &glTexSubImage2D;
	gl::Uniform1f = &glUniform1f;
	gl::Uniform1fv = &glUniform1fv;
	gl::Uniform1i = &glUniform1i;
	gl::Uniform1iv = &glUniform1iv;
	gl::Uniform2f = &glUniform2f;
	gl::Uniform2fv = &glUniform2fv;
	gl::Uniform2i = &glUniform2i;
	gl::Uniform2iv = &glUniform2iv;
	gl::Uniform3f = &glUniform3f;
	gl::Uniform3fv = &glUniform3fv;
	gl::Uniform3i = &glUniform3i;
	gl::Uniform3iv = &glUniform3iv;
	gl::Uniform4f = &glUniform4f;
	gl::Uniform4fv = &glUniform4fv;
	gl::Uniform4i = &glUniform4i;
	gl::Uniform4iv = &glUniform4iv;
	gl::UniformMatrix2fv = &glUniformMatrix2fv;
	gl::UniformMatrix3fv = &glUniformMatrix3fv;
	gl::UniformMatrix4fv = &glUniformMatrix4fv;
	gl::UseProgram = &glUseProgram;
	gl::ValidateProgram = &glValidateProgram;
	gl::VertexAttrib1f = &glVertexAttrib1f;
	gl::VertexAttrib1fv = &glVertexAttrib1fv;
	gl::VertexAttrib2f = &glVertexAttrib2f;
	gl::VertexAttrib2fv = &glVertexAttrib2fv;
	gl::VertexAttrib3f = &glVertexAttrib3f;
	gl::VertexAttrib3fv = &glVertexAttrib3fv;
	gl::VertexAttrib4f = &glVertexAttrib4f;
	gl::VertexAttrib4fv = &glVertexAttrib4fv;
	gl::VertexAttribPointer = &glVertexAttribPointer;
	gl::Viewport = &glViewport;

#if BUILD_API_MAX>=30
// Now attempt to load ES3
	gl::ReadBuffer = &glReadBuffer;
	gl::DrawRangeElements = &glDrawRangeElements;
	gl::TexImage3D = &glTexImage3D;
	gl::TexSubImage3D = &glTexSubImage3D;
	gl::CopyTexSubImage3D = &glCopyTexSubImage3D;
	gl::CompressedTexImage3D = &glCompressedTexImage3D;
	gl::CompressedTexSubImage3D = &glCompressedTexSubImage3D;
	gl::GenQueries = &glGenQueries;
	gl::DeleteQueries = &glDeleteQueries;
	gl::IsQuery = &glIsQuery;
	gl::BeginQuery = &glBeginQuery;
	gl::EndQuery = &glEndQuery;
	gl::GetQueryiv = &glGetQueryiv;
	gl::GetQueryObjectuiv = &glGetQueryObjectuiv;
	gl::UnmapBuffer = &glUnmapBuffer;
	gl::GetBufferPointerv = &glGetBufferPointerv;
	gl::DrawBuffers = &glDrawBuffers;
	gl::UniformMatrix2x3fv = &glUniformMatrix2x3fv;
	gl::UniformMatrix3x2fv = &glUniformMatrix3x2fv;
	gl::UniformMatrix2x4fv = &glUniformMatrix2x4fv;
	gl::UniformMatrix4x2fv = &glUniformMatrix4x2fv;
	gl::UniformMatrix3x4fv = &glUniformMatrix3x4fv;
	gl::UniformMatrix4x3fv = &glUniformMatrix4x3fv;
	gl::BlitFramebuffer = &glBlitFramebuffer;
	gl::RenderbufferStorageMultisample = &glRenderbufferStorageMultisample;
	gl::FramebufferTextureLayer = &glFramebufferTextureLayer;
	gl::MapBufferRange = &glMapBufferRange;
	gl::FlushMappedBufferRange = &glFlushMappedBufferRange;
	gl::BindVertexArray = &glBindVertexArray;
	gl::DeleteVertexArrays = &glDeleteVertexArrays;
	gl::GenVertexArrays = &glGenVertexArrays;
	gl::IsVertexArray = &glIsVertexArray;
	gl::GetIntegeri_v = &glGetIntegeri_v;
	gl::BeginTransformFeedback = &glBeginTransformFeedback;
	gl::EndTransformFeedback = &glEndTransformFeedback;
	gl::BindBufferRange = &glBindBufferRange;
	gl::BindBufferBase = &glBindBufferBase;
	gl::TransformFeedbackVaryings = &glTransformFeedbackVaryings;
	gl::GetTransformFeedbackVarying = &glGetTransformFeedbackVarying;
	gl::VertexAttribIPointer = &glVertexAttribIPointer;
	gl::GetVertexAttribIiv = &glGetVertexAttribIiv;
	gl::GetVertexAttribIuiv = &glGetVertexAttribIuiv;
	gl::VertexAttribI4i = &glVertexAttribI4i;
	gl::VertexAttribI4ui = &glVertexAttribI4ui;
	gl::VertexAttribI4iv = &glVertexAttribI4iv;
	gl::VertexAttribI4uiv = &glVertexAttribI4uiv;
	gl::GetUniformuiv = &glGetUniformuiv;
	gl::GetFragDataLocation = &glGetFragDataLocation;
	gl::Uniform1ui = &glUniform1ui;
	gl::Uniform2ui = &glUniform2ui;
	gl::Uniform3ui = &glUniform3ui;
	gl::Uniform4ui = &glUniform4ui;
	gl::Uniform1uiv = &glUniform1uiv;
	gl::Uniform2uiv = &glUniform2uiv;
	gl::Uniform3uiv = &glUniform3uiv;
	gl::Uniform4uiv = &glUniform4uiv;
	gl::ClearBufferiv = &glClearBufferiv;
	gl::ClearBufferuiv = &glClearBufferuiv;
	gl::ClearBufferfv = &glClearBufferfv;
	gl::ClearBufferfi = &glClearBufferfi;
	gl::GetStringi = &glGetStringi;
	gl::CopyBufferSubData = &glCopyBufferSubData;
	gl::GetUniformIndices = &glGetUniformIndices;
	gl::GetActiveUniformsiv = &glGetActiveUniformsiv;
	gl::GetUniformBlockIndex = &glGetUniformBlockIndex;
	gl::GetActiveUniformBlockiv = &glGetActiveUniformBlockiv;
	gl::GetActiveUniformBlockName = &glGetActiveUniformBlockName;
	gl::UniformBlockBinding = &glUniformBlockBinding;
	gl::DrawArraysInstanced = &glDrawArraysInstanced;
	gl::DrawElementsInstanced = &glDrawElementsInstanced;
	gl::FenceSync = &glFenceSync;
	gl::IsSync = &glIsSync;
	gl::DeleteSync = &glDeleteSync;
	gl::ClientWaitSync = &glClientWaitSync;
	gl::WaitSync = &glWaitSync;
	gl::GetInteger64v = &glGetInteger64v;
	gl::GetSynciv = &glGetSynciv;
	gl::GetInteger64i_v = &glGetInteger64i_v;
	gl::GetBufferParameteri64v = &glGetBufferParameteri64v;
	gl::GenSamplers = &glGenSamplers;
	gl::DeleteSamplers = &glDeleteSamplers;
	gl::IsSampler = &glIsSampler;
	gl::BindSampler = &glBindSampler;
	gl::SamplerParameteri = &glSamplerParameteri;
	gl::SamplerParameteriv = &glSamplerParameteriv;
	gl::SamplerParameterf = &glSamplerParameterf;
	gl::SamplerParameterfv = &glSamplerParameterfv;
	gl::GetSamplerParameteriv = &glGetSamplerParameteriv;
	gl::GetSamplerParameterfv = &glGetSamplerParameterfv;
	gl::VertexAttribDivisor = &glVertexAttribDivisor;
	gl::BindTransformFeedback = &glBindTransformFeedback;
	gl::DeleteTransformFeedbacks = &glDeleteTransformFeedbacks;
	gl::GenTransformFeedbacks = &glGenTransformFeedbacks;
	gl::IsTransformFeedback = &glIsTransformFeedback;
	gl::PauseTransformFeedback = &glPauseTransformFeedback;
	gl::ResumeTransformFeedback = &glResumeTransformFeedback;
	gl::GetProgramBinary = &glGetProgramBinary;
	gl::ProgramBinary = &glProgramBinary;
	gl::ProgramParameteri = &glProgramParameteri;
	gl::InvalidateFramebuffer = &glInvalidateFramebuffer;
	gl::InvalidateSubFramebuffer = &glInvalidateSubFramebuffer;
	gl::TexStorage2D = &glTexStorage2D;
	gl::TexStorage3D = &glTexStorage3D;
	gl::GetInternalformativ = &glGetInternalformativ;

#endif

#if BUILD_API_MAX>=31
// Now attempt to load ES3.1
	gl::DispatchCompute = &glDispatchCompute;
	gl::DispatchComputeIndirect = &glDispatchComputeIndirect;
	gl::BindImageTexture = &glBindImageTexture;
	gl::MemoryBarrier = &glMemoryBarrier;
	gl::MemoryBarrierByRegion = &glMemoryBarrierByRegion;
	gl::BindProgramPipeline = &glBindProgramPipeline;
	gl::DeleteProgramPipelines = &glDeleteProgramPipelines;
	gl::GenProgramPipelines = &glGenProgramPipelines;
	gl::IsProgramPipeline = &glIsProgramPipeline;
	gl::GetProgramPipelineiv = &glGetProgramPipelineiv;
	gl::ValidateProgramPipeline = &glValidateProgramPipeline;
	gl::GetProgramPipelineInfoLog = &glGetProgramPipelineInfoLog;
	gl::UseProgramStages = &glUseProgramStages;
	gl::ActiveShaderProgram = &glActiveShaderProgram;
	gl::ProgramUniform1i = &glProgramUniform1i;
	gl::ProgramUniform2i = &glProgramUniform2i;
	gl::ProgramUniform3i = &glProgramUniform3i;
	gl::ProgramUniform4i = &glProgramUniform4i;
	gl::ProgramUniform1ui = &glProgramUniform1ui;
	gl::ProgramUniform2ui = &glProgramUniform2ui;
	gl::ProgramUniform3ui = &glProgramUniform3ui;
	gl::ProgramUniform4ui = &glProgramUniform4ui;
	gl::ProgramUniform1f = &glProgramUniform1f;
	gl::ProgramUniform2f = &glProgramUniform2f;
	gl::ProgramUniform3f = &glProgramUniform3f;
	gl::ProgramUniform4f = &glProgramUniform4f;
	gl::ProgramUniform1iv = &glProgramUniform1iv;
	gl::ProgramUniform2iv = &glProgramUniform2iv;
	gl::ProgramUniform3iv = &glProgramUniform3iv;
	gl::ProgramUniform4iv = &glProgramUniform4iv;
	gl::ProgramUniform1uiv = &glProgramUniform1uiv;
	gl::ProgramUniform2uiv = &glProgramUniform2uiv;
	gl::ProgramUniform3uiv = &glProgramUniform3uiv;
	gl::ProgramUniform4uiv = &glProgramUniform4uiv;
	gl::ProgramUniform1fv = &glProgramUniform1fv;
	gl::ProgramUniform2fv = &glProgramUniform2fv;
	gl::ProgramUniform3fv = &glProgramUniform3fv;
	gl::ProgramUniform4fv = &glProgramUniform4fv;
	gl::ProgramUniformMatrix2fv = &glProgramUniformMatrix2fv;
	gl::ProgramUniformMatrix3fv = &glProgramUniformMatrix3fv;
	gl::ProgramUniformMatrix4fv = &glProgramUniformMatrix4fv;
	gl::ProgramUniformMatrix2x3fv = &glProgramUniformMatrix2x3fv;
	gl::ProgramUniformMatrix3x2fv = &glProgramUniformMatrix3x2fv;
	gl::ProgramUniformMatrix2x4fv = &glProgramUniformMatrix2x4fv;
	gl::ProgramUniformMatrix4x2fv = &glProgramUniformMatrix4x2fv;
	gl::ProgramUniformMatrix3x4fv = &glProgramUniformMatrix3x4fv;
	gl::ProgramUniformMatrix4x3fv = &glProgramUniformMatrix4x3fv;
	gl::CreateShaderProgramv = &glCreateShaderProgramv;
	gl::DrawArraysIndirect = &glDrawArraysIndirect;
	gl::DrawElementsIndirect = &glDrawElementsIndirect;
	gl::TexStorage2DMultisample = &glTexStorage2DMultisample;
	gl::SampleMaski = &glSampleMaski;
	gl::BindVertexBuffer = &glBindVertexBuffer;
	gl::VertexAttribFormat = &glVertexAttribFormat;
	gl::VertexAttribIFormat = &glVertexAttribIFormat;
	gl::VertexAttribBinding = &glVertexAttribBinding;
	gl::VertexBindingDivisor = &glVertexBindingDivisor;
	gl::FramebufferParameteri = &glFramebufferParameteri;
	gl::GetFramebufferParameteriv = &glGetFramebufferParameteriv;
	gl::GetProgramInterfaceiv = &glGetProgramInterfaceiv;
	gl::GetProgramResourceIndex = &glGetProgramResourceIndex;
	gl::GetProgramResourceName = &glGetProgramResourceName;
	gl::GetProgramResourceiv = &glGetProgramResourceiv;
	gl::GetProgramResourceLocation = &glGetProgramResourceLocation;
	gl::GetBooleani_v = &glGetBooleani_v;
	gl::GetMultisamplefv = &glGetMultisamplefv;
	gl::GetTexLevelParameteriv = &glGetTexLevelParameteriv;
	gl::GetTexLevelParameterfv = (PROC_ES31_glGetTexLevelParameterfv)glesLibrary().getFunction("glGetTexLevelParameterfv");

#endif
#endif //TARGET_OS_IPHONE
}

//STANDARD GUARANTEES ZERO-INITIALIZATION for static members.
PROC_ES2_glActiveTexture gl::ActiveTexture;
PROC_ES2_glAttachShader gl::AttachShader;
PROC_ES2_glBindAttribLocation gl::BindAttribLocation;
PROC_ES2_glBindBuffer gl::BindBuffer;
PROC_ES2_glBindFramebuffer gl::BindFramebuffer;
PROC_ES2_glBindRenderbuffer gl::BindRenderbuffer;
PROC_ES2_glBindTexture gl::BindTexture;
PROC_ES2_glBlendColor gl::BlendColor;
PROC_ES2_glBlendEquation gl::BlendEquation;
PROC_ES2_glBlendEquationSeparate gl::BlendEquationSeparate;
PROC_ES2_glBlendFunc gl::BlendFunc;
PROC_ES2_glBlendFuncSeparate gl::BlendFuncSeparate;
PROC_ES2_glBufferData gl::BufferData;
PROC_ES2_glBufferSubData gl::BufferSubData;
PROC_ES2_glCheckFramebufferStatus gl::CheckFramebufferStatus;
PROC_ES2_glClear gl::Clear;
PROC_ES2_glClearColor gl::ClearColor;
PROC_ES2_glClearDepthf gl::ClearDepthf;
PROC_ES2_glClearStencil gl::ClearStencil;
PROC_ES2_glColorMask gl::ColorMask;
PROC_ES2_glCompileShader gl::CompileShader;
PROC_ES2_glCompressedTexImage2D gl::CompressedTexImage2D;
PROC_ES2_glCompressedTexSubImage2D gl::CompressedTexSubImage2D;
PROC_ES2_glCopyTexImage2D gl::CopyTexImage2D;
PROC_ES2_glCopyTexSubImage2D gl::CopyTexSubImage2D;
PROC_ES2_glCreateProgram gl::CreateProgram;
PROC_ES2_glCreateShader gl::CreateShader;
PROC_ES2_glCullFace gl::CullFace;
PROC_ES2_glDeleteBuffers gl::DeleteBuffers;
PROC_ES2_glDeleteFramebuffers gl::DeleteFramebuffers;
PROC_ES2_glDeleteTextures gl::DeleteTextures;
PROC_ES2_glDeleteProgram gl::DeleteProgram;
PROC_ES2_glDeleteRenderbuffers gl::DeleteRenderbuffers;
PROC_ES2_glDeleteShader gl::DeleteShader;
PROC_ES2_glDetachShader gl::DetachShader;
PROC_ES2_glDepthFunc gl::DepthFunc;
PROC_ES2_glDepthMask gl::DepthMask;
PROC_ES2_glDepthRangef gl::DepthRangef;
PROC_ES2_glDisable gl::Disable;
PROC_ES2_glDisableVertexAttribArray gl::DisableVertexAttribArray;
PROC_ES2_glDrawArrays gl::DrawArrays;
PROC_ES2_glDrawElements gl::DrawElements;
PROC_ES2_glEnable gl::Enable;
PROC_ES2_glEnableVertexAttribArray gl::EnableVertexAttribArray;
PROC_ES2_glFinish gl::Finish;
PROC_ES2_glFlush gl::Flush;
PROC_ES2_glFramebufferRenderbuffer gl::FramebufferRenderbuffer;
PROC_ES2_glFramebufferTexture2D gl::FramebufferTexture2D;
PROC_ES2_glFrontFace gl::FrontFace;
PROC_ES2_glGenBuffers gl::GenBuffers;
PROC_ES2_glGenerateMipmap gl::GenerateMipmap;
PROC_ES2_glGenFramebuffers gl::GenFramebuffers;
PROC_ES2_glGenRenderbuffers gl::GenRenderbuffers;
PROC_ES2_glGenTextures gl::GenTextures;
PROC_ES2_glGetActiveAttrib gl::GetActiveAttrib;
PROC_ES2_glGetActiveUniform gl::GetActiveUniform;
PROC_ES2_glGetAttachedShaders gl::GetAttachedShaders;
PROC_ES2_glGetAttribLocation gl::GetAttribLocation;
PROC_ES2_glGetBooleanv gl::GetBooleanv;
PROC_ES2_glGetBufferParameteriv gl::GetBufferParameteriv;
PROC_ES2_glGetError gl::GetError;
PROC_ES2_glGetFloatv gl::GetFloatv;
PROC_ES2_glGetFramebufferAttachmentParameteriv gl::GetFramebufferAttachmentParameteriv;
PROC_ES2_glGetIntegerv gl::GetIntegerv;
PROC_ES2_glGetProgramiv gl::GetProgramiv;
PROC_ES2_glGetProgramInfoLog gl::GetProgramInfoLog;
PROC_ES2_glGetRenderbufferParameteriv gl::GetRenderbufferParameteriv;
PROC_ES2_glGetShaderiv gl::GetShaderiv;
PROC_ES2_glGetShaderInfoLog gl::GetShaderInfoLog;
PROC_ES2_glGetShaderPrecisionFormat gl::GetShaderPrecisionFormat;
PROC_ES2_glGetShaderSource gl::GetShaderSource;
PROC_ES2_glGetString gl::GetString;
PROC_ES2_glGetTexParameterfv gl::GetTexParameterfv;
PROC_ES2_glGetTexParameteriv gl::GetTexParameteriv;
PROC_ES2_glGetUniformfv gl::GetUniformfv;
PROC_ES2_glGetUniformiv gl::GetUniformiv;
PROC_ES2_glGetUniformLocation gl::GetUniformLocation;
PROC_ES2_glGetVertexAttribfv gl::GetVertexAttribfv;
PROC_ES2_glGetVertexAttribiv gl::GetVertexAttribiv;
PROC_ES2_glGetVertexAttribPointerv gl::GetVertexAttribPointerv;
PROC_ES2_glHint gl::Hint;
PROC_ES2_glIsBuffer gl::IsBuffer;
PROC_ES2_glIsEnabled gl::IsEnabled;
PROC_ES2_glIsFramebuffer gl::IsFramebuffer;
PROC_ES2_glIsProgram gl::IsProgram;
PROC_ES2_glIsRenderbuffer gl::IsRenderbuffer;
PROC_ES2_glIsShader gl::IsShader;
PROC_ES2_glIsTexture gl::IsTexture;
PROC_ES2_glLineWidth gl::LineWidth;
PROC_ES2_glLinkProgram gl::LinkProgram;
PROC_ES2_glPixelStorei gl::PixelStorei;
PROC_ES2_glPolygonOffset gl::PolygonOffset;
PROC_ES2_glReadPixels gl::ReadPixels;
PROC_ES2_glReleaseShaderCompiler gl::ReleaseShaderCompiler;
PROC_ES2_glRenderbufferStorage gl::RenderbufferStorage;
PROC_ES2_glSampleCoverage gl::SampleCoverage;
PROC_ES2_glScissor gl::Scissor;
PROC_ES2_glShaderBinary gl::ShaderBinary;
PROC_ES2_glShaderSource gl::ShaderSource;
PROC_ES2_glStencilFunc gl::StencilFunc;
PROC_ES2_glStencilFuncSeparate gl::StencilFuncSeparate;
PROC_ES2_glStencilMask gl::StencilMask;
PROC_ES2_glStencilMaskSeparate gl::StencilMaskSeparate;
PROC_ES2_glStencilOp gl::StencilOp;
PROC_ES2_glStencilOpSeparate gl::StencilOpSeparate;
PROC_ES2_glTexImage2D gl::TexImage2D;
PROC_ES2_glTexParameterf gl::TexParameterf;
PROC_ES2_glTexParameterfv gl::TexParameterfv;
PROC_ES2_glTexParameteri gl::TexParameteri;
PROC_ES2_glTexParameteriv gl::TexParameteriv;
PROC_ES2_glTexSubImage2D gl::TexSubImage2D;
PROC_ES2_glUniform1f gl::Uniform1f;
PROC_ES2_glUniform1fv gl::Uniform1fv;
PROC_ES2_glUniform1i gl::Uniform1i;
PROC_ES2_glUniform1iv gl::Uniform1iv;
PROC_ES2_glUniform2f gl::Uniform2f;
PROC_ES2_glUniform2fv gl::Uniform2fv;
PROC_ES2_glUniform2i gl::Uniform2i;
PROC_ES2_glUniform2iv gl::Uniform2iv;
PROC_ES2_glUniform3f gl::Uniform3f;
PROC_ES2_glUniform3fv gl::Uniform3fv;
PROC_ES2_glUniform3i gl::Uniform3i;
PROC_ES2_glUniform3iv gl::Uniform3iv;
PROC_ES2_glUniform4f gl::Uniform4f;
PROC_ES2_glUniform4fv gl::Uniform4fv;
PROC_ES2_glUniform4i gl::Uniform4i;
PROC_ES2_glUniform4iv gl::Uniform4iv;
PROC_ES2_glUniformMatrix2fv gl::UniformMatrix2fv;
PROC_ES2_glUniformMatrix3fv gl::UniformMatrix3fv;
PROC_ES2_glUniformMatrix4fv gl::UniformMatrix4fv;
PROC_ES2_glUseProgram gl::UseProgram;
PROC_ES2_glValidateProgram gl::ValidateProgram;
PROC_ES2_glVertexAttrib1f gl::VertexAttrib1f;
PROC_ES2_glVertexAttrib1fv gl::VertexAttrib1fv;
PROC_ES2_glVertexAttrib2f gl::VertexAttrib2f;
PROC_ES2_glVertexAttrib2fv gl::VertexAttrib2fv;
PROC_ES2_glVertexAttrib3f gl::VertexAttrib3f;
PROC_ES2_glVertexAttrib3fv gl::VertexAttrib3fv;
PROC_ES2_glVertexAttrib4f gl::VertexAttrib4f;
PROC_ES2_glVertexAttrib4fv gl::VertexAttrib4fv;
PROC_ES2_glVertexAttribPointer gl::VertexAttribPointer;
PROC_ES2_glViewport gl::Viewport;

#if BUILD_API_MAX>=30
// Es3 functions
PROC_ES3_glReadBuffer gl::ReadBuffer;
PROC_ES3_glDrawRangeElements gl::DrawRangeElements;
PROC_ES3_glTexImage3D gl::TexImage3D;
PROC_ES3_glTexSubImage3D gl::TexSubImage3D;
PROC_ES3_glCopyTexSubImage3D gl::CopyTexSubImage3D;
PROC_ES3_glCompressedTexImage3D gl::CompressedTexImage3D;
PROC_ES3_glCompressedTexSubImage3D gl::CompressedTexSubImage3D;
PROC_ES3_glGenQueries gl::GenQueries;
PROC_ES3_glDeleteQueries gl::DeleteQueries;
PROC_ES3_glIsQuery gl::IsQuery;
PROC_ES3_glBeginQuery gl::BeginQuery;
PROC_ES3_glEndQuery gl::EndQuery;
PROC_ES3_glGetQueryiv gl::GetQueryiv;
PROC_ES3_glGetQueryObjectuiv gl::GetQueryObjectuiv;
PROC_ES3_glUnmapBuffer gl::UnmapBuffer;
PROC_ES3_glGetBufferPointerv gl::GetBufferPointerv;
PROC_ES3_glDrawBuffers gl::DrawBuffers;
PROC_ES3_glUniformMatrix2x3fv gl::UniformMatrix2x3fv;
PROC_ES3_glUniformMatrix3x2fv gl::UniformMatrix3x2fv;
PROC_ES3_glUniformMatrix2x4fv gl::UniformMatrix2x4fv;
PROC_ES3_glUniformMatrix4x2fv gl::UniformMatrix4x2fv;
PROC_ES3_glUniformMatrix3x4fv gl::UniformMatrix3x4fv;
PROC_ES3_glUniformMatrix4x3fv gl::UniformMatrix4x3fv;
PROC_ES3_glBlitFramebuffer gl::BlitFramebuffer;
PROC_ES3_glRenderbufferStorageMultisample gl::RenderbufferStorageMultisample;
PROC_ES3_glFramebufferTextureLayer gl::FramebufferTextureLayer;
PROC_ES3_glMapBufferRange gl::MapBufferRange;
PROC_ES3_glFlushMappedBufferRange gl::FlushMappedBufferRange;
PROC_ES3_glBindVertexArray gl::BindVertexArray;
PROC_ES3_glDeleteVertexArrays gl::DeleteVertexArrays;
PROC_ES3_glGenVertexArrays gl::GenVertexArrays;
PROC_ES3_glIsVertexArray gl::IsVertexArray;
PROC_ES3_glGetIntegeri_v gl::GetIntegeri_v;
PROC_ES3_glBeginTransformFeedback gl::BeginTransformFeedback;
PROC_ES3_glEndTransformFeedback gl::EndTransformFeedback;
PROC_ES3_glBindBufferRange gl::BindBufferRange;
PROC_ES3_glBindBufferBase gl::BindBufferBase;
PROC_ES3_glTransformFeedbackVaryings gl::TransformFeedbackVaryings;
PROC_ES3_glGetTransformFeedbackVarying gl::GetTransformFeedbackVarying;
PROC_ES3_glVertexAttribIPointer gl::VertexAttribIPointer;
PROC_ES3_glGetVertexAttribIiv gl::GetVertexAttribIiv;
PROC_ES3_glGetVertexAttribIuiv gl::GetVertexAttribIuiv;
PROC_ES3_glVertexAttribI4i gl::VertexAttribI4i;
PROC_ES3_glVertexAttribI4ui gl::VertexAttribI4ui;
PROC_ES3_glVertexAttribI4iv gl::VertexAttribI4iv;
PROC_ES3_glVertexAttribI4uiv gl::VertexAttribI4uiv;
PROC_ES3_glGetUniformuiv gl::GetUniformuiv;
PROC_ES3_glGetFragDataLocation gl::GetFragDataLocation;
PROC_ES3_glUniform1ui gl::Uniform1ui;
PROC_ES3_glUniform2ui gl::Uniform2ui;
PROC_ES3_glUniform3ui gl::Uniform3ui;
PROC_ES3_glUniform4ui gl::Uniform4ui;
PROC_ES3_glUniform1uiv gl::Uniform1uiv;
PROC_ES3_glUniform2uiv gl::Uniform2uiv;
PROC_ES3_glUniform3uiv gl::Uniform3uiv;
PROC_ES3_glUniform4uiv gl::Uniform4uiv;
PROC_ES3_glClearBufferiv gl::ClearBufferiv;
PROC_ES3_glClearBufferuiv gl::ClearBufferuiv;
PROC_ES3_glClearBufferfv gl::ClearBufferfv;
PROC_ES3_glClearBufferfi gl::ClearBufferfi;
PROC_ES3_glGetStringi gl::GetStringi;
PROC_ES3_glCopyBufferSubData gl::CopyBufferSubData;
PROC_ES3_glGetUniformIndices gl::GetUniformIndices;
PROC_ES3_glGetActiveUniformsiv gl::GetActiveUniformsiv;
PROC_ES3_glGetUniformBlockIndex gl::GetUniformBlockIndex;
PROC_ES3_glGetActiveUniformBlockiv gl::GetActiveUniformBlockiv;
PROC_ES3_glGetActiveUniformBlockName gl::GetActiveUniformBlockName;
PROC_ES3_glUniformBlockBinding gl::UniformBlockBinding;
PROC_ES3_glDrawArraysInstanced gl::DrawArraysInstanced;
PROC_ES3_glDrawElementsInstanced gl::DrawElementsInstanced;
PROC_ES3_glFenceSync gl::FenceSync;
PROC_ES3_glIsSync gl::IsSync;
PROC_ES3_glDeleteSync gl::DeleteSync;
PROC_ES3_glClientWaitSync gl::ClientWaitSync;
PROC_ES3_glWaitSync gl::WaitSync;
PROC_ES3_glGetInteger64v gl::GetInteger64v;
PROC_ES3_glGetSynciv gl::GetSynciv;
PROC_ES3_glGetInteger64i_v gl::GetInteger64i_v;
PROC_ES3_glGetBufferParameteri64v gl::GetBufferParameteri64v;
PROC_ES3_glGenSamplers gl::GenSamplers;
PROC_ES3_glDeleteSamplers gl::DeleteSamplers;
PROC_ES3_glIsSampler gl::IsSampler;
PROC_ES3_glBindSampler gl::BindSampler;
PROC_ES3_glSamplerParameteri gl::SamplerParameteri;
PROC_ES3_glSamplerParameteriv gl::SamplerParameteriv;
PROC_ES3_glSamplerParameterf gl::SamplerParameterf;
PROC_ES3_glSamplerParameterfv gl::SamplerParameterfv;
PROC_ES3_glGetSamplerParameteriv gl::GetSamplerParameteriv;
PROC_ES3_glGetSamplerParameterfv gl::GetSamplerParameterfv;
PROC_ES3_glVertexAttribDivisor gl::VertexAttribDivisor;
PROC_ES3_glBindTransformFeedback gl::BindTransformFeedback;
PROC_ES3_glDeleteTransformFeedbacks gl::DeleteTransformFeedbacks;
PROC_ES3_glGenTransformFeedbacks gl::GenTransformFeedbacks;
PROC_ES3_glIsTransformFeedback gl::IsTransformFeedback;
PROC_ES3_glPauseTransformFeedback gl::PauseTransformFeedback;
PROC_ES3_glResumeTransformFeedback gl::ResumeTransformFeedback;
PROC_ES3_glGetProgramBinary gl::GetProgramBinary;
PROC_ES3_glProgramBinary gl::ProgramBinary;
PROC_ES3_glProgramParameteri gl::ProgramParameteri;
PROC_ES3_glInvalidateFramebuffer gl::InvalidateFramebuffer;
PROC_ES3_glInvalidateSubFramebuffer gl::InvalidateSubFramebuffer;
PROC_ES3_glTexStorage2D gl::TexStorage2D;
PROC_ES3_glTexStorage3D gl::TexStorage3D;
PROC_ES3_glGetInternalformativ gl::GetInternalformativ;
#endif

//#if BUILD_API_MAX>=31
// Es3.1 functions
PROC_ES31_glDispatchCompute gl::DispatchCompute;
PROC_ES31_glDispatchComputeIndirect gl::DispatchComputeIndirect;
PROC_ES31_glBindImageTexture gl::BindImageTexture;
PROC_ES31_glMemoryBarrier gl::MemoryBarrier;
PROC_ES31_glMemoryBarrierByRegion gl::MemoryBarrierByRegion;
PROC_ES31_glBindProgramPipeline gl::BindProgramPipeline;
PROC_ES31_glDeleteProgramPipelines gl::DeleteProgramPipelines;
PROC_ES31_glGenProgramPipelines gl::GenProgramPipelines;
PROC_ES31_glIsProgramPipeline gl::IsProgramPipeline;
PROC_ES31_glGetProgramPipelineiv gl::GetProgramPipelineiv;
PROC_ES31_glValidateProgramPipeline gl::ValidateProgramPipeline;
PROC_ES31_glGetProgramPipelineInfoLog gl::GetProgramPipelineInfoLog;
PROC_ES31_glUseProgramStages gl::UseProgramStages;
PROC_ES31_glActiveShaderProgram gl::ActiveShaderProgram;
PROC_ES31_glProgramUniform1i gl::ProgramUniform1i;
PROC_ES31_glProgramUniform2i gl::ProgramUniform2i;
PROC_ES31_glProgramUniform3i gl::ProgramUniform3i;
PROC_ES31_glProgramUniform4i gl::ProgramUniform4i;
PROC_ES31_glProgramUniform1ui gl::ProgramUniform1ui;
PROC_ES31_glProgramUniform2ui gl::ProgramUniform2ui;
PROC_ES31_glProgramUniform3ui gl::ProgramUniform3ui;
PROC_ES31_glProgramUniform4ui gl::ProgramUniform4ui;
PROC_ES31_glProgramUniform1f gl::ProgramUniform1f;
PROC_ES31_glProgramUniform2f gl::ProgramUniform2f;
PROC_ES31_glProgramUniform3f gl::ProgramUniform3f;
PROC_ES31_glProgramUniform4f gl::ProgramUniform4f;
PROC_ES31_glProgramUniform1iv gl::ProgramUniform1iv;
PROC_ES31_glProgramUniform2iv gl::ProgramUniform2iv;
PROC_ES31_glProgramUniform3iv gl::ProgramUniform3iv;
PROC_ES31_glProgramUniform4iv gl::ProgramUniform4iv;
PROC_ES31_glProgramUniform1uiv gl::ProgramUniform1uiv;
PROC_ES31_glProgramUniform2uiv gl::ProgramUniform2uiv;
PROC_ES31_glProgramUniform3uiv gl::ProgramUniform3uiv;
PROC_ES31_glProgramUniform4uiv gl::ProgramUniform4uiv;
PROC_ES31_glProgramUniform1fv gl::ProgramUniform1fv;
PROC_ES31_glProgramUniform2fv gl::ProgramUniform2fv;
PROC_ES31_glProgramUniform3fv gl::ProgramUniform3fv;
PROC_ES31_glProgramUniform4fv gl::ProgramUniform4fv;
PROC_ES31_glProgramUniformMatrix2fv gl::ProgramUniformMatrix2fv;
PROC_ES31_glProgramUniformMatrix3fv gl::ProgramUniformMatrix3fv;
PROC_ES31_glProgramUniformMatrix4fv gl::ProgramUniformMatrix4fv;
PROC_ES31_glProgramUniformMatrix2x3fv gl::ProgramUniformMatrix2x3fv;
PROC_ES31_glProgramUniformMatrix3x2fv gl::ProgramUniformMatrix3x2fv;
PROC_ES31_glProgramUniformMatrix2x4fv gl::ProgramUniformMatrix2x4fv;
PROC_ES31_glProgramUniformMatrix4x2fv gl::ProgramUniformMatrix4x2fv;
PROC_ES31_glProgramUniformMatrix3x4fv gl::ProgramUniformMatrix3x4fv;
PROC_ES31_glProgramUniformMatrix4x3fv gl::ProgramUniformMatrix4x3fv;
PROC_ES31_glCreateShaderProgramv gl::CreateShaderProgramv;
PROC_ES31_glDrawArraysIndirect gl::DrawArraysIndirect;
PROC_ES31_glDrawElementsIndirect gl::DrawElementsIndirect;
PROC_ES31_glTexStorage2DMultisample gl::TexStorage2DMultisample;
PROC_ES31_glSampleMaski gl::SampleMaski;
PROC_ES31_glBindVertexBuffer gl::BindVertexBuffer;
PROC_ES31_glVertexAttribFormat gl::VertexAttribFormat;
PROC_ES31_glVertexAttribIFormat gl::VertexAttribIFormat;
PROC_ES31_glVertexAttribBinding gl::VertexAttribBinding;
PROC_ES31_glVertexBindingDivisor gl::VertexBindingDivisor;
PROC_ES31_glFramebufferParameteri gl::FramebufferParameteri;
PROC_ES31_glGetFramebufferParameteriv gl::GetFramebufferParameteriv;
PROC_ES31_glGetProgramInterfaceiv gl::GetProgramInterfaceiv;
PROC_ES31_glGetProgramResourceIndex gl::GetProgramResourceIndex;
PROC_ES31_glGetProgramResourceName gl::GetProgramResourceName;
PROC_ES31_glGetProgramResourceiv gl::GetProgramResourceiv;
PROC_ES31_glGetProgramResourceLocation gl::GetProgramResourceLocation;
PROC_ES31_glGetBooleani_v gl::GetBooleani_v;
PROC_ES31_glGetMultisamplefv gl::GetMultisamplefv;
PROC_ES31_glGetTexLevelParameteriv gl::GetTexLevelParameteriv;
PROC_ES31_glGetTexLevelParameterfv gl::GetTexLevelParameterfv;
//#endif
//!\endcond
