// Applies the Android plugin for Gradle to this build and makes the android block available to specify Android-specific build options
plugins { id 'com.android.application' }

// The set of framework projects on which this application is dependent
def projectDependencies = ["PVRShell", "PVRUtilsVk"]

// This block configures the repositories and dependencies for Gradle itself. Here we add a dependency for the Android plugin for Gradle as it provides
// the additional instructions Gradle needs to build Android app modules
// This block configures the repositories and dependencies used by all modules in the project
android {
namespace = "com.powervr.VulkanNeuralNetworkEnvironment"
defaultConfig {
		applicationId "com.powervr.VulkanNeuralNetworkEnvironment"
externalNativeBuild {
			cmake {
				cppFlags "-fexceptions"
				arguments "-DANDROID_STL=c++_static", "-DPVR_PREBUILT_DEPENDENCIES=ON", "-DPVR_ENABLE_INSTALL=ON"
			}
		}
}
	

	// This block configures our build types
	buildTypes {
		release {
			minifyEnabled false
			proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-rules.pro'
			zipAlignEnabled true
		}
		debug {
			sourceSets {
				main {
					jniLibs {
						// We are providing prebuilt validation layer libraries built using the LunarG Vulkan-LoaderAndValidationLayers github repo: https://github.com/KhronosGroup/Vulkan-LoaderAndValidationLayers.git
						// We found that the latest set provided in the ndk were quite out of date (using VK_HEADER_VERSION 31) and were outputting false positive validation layer errors in certain cases.
						// The following makes use of our provided validation layer libraries:
						srcDir "${project.projectDir}/../../../../external/validation_layers/jniLibs"
						
						// The following will instead make use of the prebuilt validation layer libraries provided in the ndk:
						//def ndkDir = android.ndkDirectory
						//srcDir "$ndkDir/sources/third_party/vulkan/src/build-android/jniLibs"
					}
				}
			}
		}
	}
	externalNativeBuild {
		cmake {

			path = "../CMakeLists.txt"

			version = "3.22.1"
		}
	}

	// Ensure that the icons are copied early - we do this by making the preBuild task depends on the copyIcons task
	tasks.register('copyIcons', Copy) {
		from file("${project.projectDir}/../../../../res/Android/Vulkan")
		into sourceSets.main.res.srcDirs[0]
		filePermissions { unix(0664) }
	}
	preBuild.dependsOn copyIcons

	// Add to this list files that will need to be read at runtime here: Textures, shaders, text files etc.
	FileCollection assetFiles = files(
	"${project.projectDir}/../../../assets/damagedHelmet/damagedHelmet.bin",
	"${project.projectDir}/../../../assets/damagedHelmet/damagedHelmet.gltf",
	"${project.projectDir}/../../../assets/damagedHelmet/Default_albedo.pvr",
	"${project.projectDir}/../../../assets/damagedHelmet/Default_albedo_astc.pvr",
	"${project.projectDir}/../../../assets/damagedHelmet/Default_emissive.pvr",
	"${project.projectDir}/../../../assets/damagedHelmet/Default_emissive_astc.pvr",
	"${project.projectDir}/../../../assets/damagedHelmet/Default_occlusionRoughnessMetallic.pvr",
	"${project.projectDir}/../../../assets/damagedHelmet/Default_occlusionRoughnessMetallic_astc.pvr",
	"${project.projectDir}/../../../assets/damagedHelmet/Default_normal.pvr",
	"${project.projectDir}/../../../assets/damagedHelmet/Default_normal_astc.pvr",
	"${project.projectDir}/../../../assets/Environments/quarry_r9g9b9e5.pvr",
	"${project.projectDir}/../../../assets/Environments/quarry_r9g9b9e5_Irradiance.pvr",
	"${project.projectDir}/../../../assets/Environments/quarry_r9g9b9e5_Prefiltered.pvr",
	"${project.projectDir}/../../../assets/Environments/quarry_equirectangular_r9g9b9e5.pvr",
	"${project.projectDir}/../../../assets/PBR/brdfLUT.pvr",
	"${project.projectDir}/../../../assets/NeuralNetworks/quarry_equirectangular_r9g9b9e5.blob",
	"${project.projectDir}/../PBRFragShader.fsh.spv",
	"${project.projectDir}/../SkyboxFragShader.fsh.spv",
	"${project.projectDir}/../SkyboxVertShader.vsh.spv",
	"${project.projectDir}/../VertShader.vsh.spv",
	"${project.projectDir}/../NeuralNetworkEnvironmentCooperativeMatrix.csh",
	"${project.projectDir}/../ScreenSpaceBox.csh",
	"${project.projectDir}/../OrganizePatchWorkload.csh",
	"${project.projectDir}/../NeuralNetworkEnvironment.csh"
	)
	
	// Add a task for copying our assets from their original location (${project.projectDir}...) to the assets/ folder for packaging
	tasks.register('copyAssetsDebug', Copy) {
		from assetFiles
		into sourceSets.main.assets.srcDirs[0]
		filePermissions { unix(0664) }
	}
	
	tasks.register('copyAssetsRelease', Copy) {
		from assetFiles
		into sourceSets.main.assets.srcDirs[0]
		filePermissions { unix(0664) }
	}
}

// This block specifies dependencies required to build only the module itself
dependencies {
	// Dependency on local binaries
	implementation fileTree(dir: 'libs', include: ['*.jar'])
	implementation project(':PVRShell')
    implementation project(':PVRUtilsVk')
}



