plugins { id 'com.android.library' }

android {
namespace = "com.powervr.DUMMY"
defaultConfig {
versionCode = 1
versionName = "1.0"
		externalNativeBuild {
			cmake {
				cppFlags "-fexceptions"
				arguments "-DANDROID_STL=c++_static", "-DPVRVK_USE_PLATFORM=VK_USE_PLATFORM_ANDROID_KHR", "-DPVRVK_ENABLE_INSTALL=ON"
				targets "PVRVk"
			}
		}
}
	externalNativeBuild {
		cmake {

			path = "../CMakeLists.txt"
}
	}
}


