// Applies the Android plugin for Gradle to this build and makes the android block available to specify Android-specific build options
plugins { id 'com.android.application' }

// The set of framework projects on which this application is dependent
def projectDependencies = ["PVRShell", "PVRUtilsGles"]

// This block configures the repositories and dependencies for Gradle itself. Here we add a dependency for the Android plugin for Gradle as it provides
// the additional instructions Gradle needs to build Android app modules
// This block configures the repositories and dependencies used by all modules in the project
android {
namespace = "com.powervr.OpenGLESShadows"
defaultConfig {
		applicationId "com.powervr.OpenGLESShadows"
externalNativeBuild {
			cmake {
				cppFlags "-fexceptions"
				arguments "-DANDROID_STL=c++_static", "-DPVR_PREBUILT_DEPENDENCIES=ON", "-DPVR_ENABLE_INSTALL=ON"
			}
		}
}
	

	// This block configures our build types
	buildTypes {
		release {
			minifyEnabled false
			proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-rules.pro'
			zipAlignEnabled true
		}
	}
	externalNativeBuild {
		cmake {

			path = "../CMakeLists.txt"
}
	}

	// Ensure that the icons are copied early - we do this by making the preBuild task depends on the copyIcons task
	tasks.register('copyIcons', Copy) {
		from file("${project.projectDir}/../../../../res/Android/OpenGLES")
		into sourceSets.main.res.srcDirs[0]
		filePermissions { unix(0664) }
	}
	preBuild.dependsOn copyIcons

	// Add to this list files that will need to be read at runtime here: Textures, shaders, text files etc.
	FileCollection assetFiles = files(
	"${project.projectDir}/../AmbientFragShader.fsh",
	"${project.projectDir}/../GaussianBlurHorizontalFragShader.fsh",
	"${project.projectDir}/../GaussianBlurVerticalFragShader.fsh",
	"${project.projectDir}/../LightingFragShader.fsh",
	"${project.projectDir}/../MeshFragShader.fsh",
	"${project.projectDir}/../ShadowFragShader.fsh",
	"${project.projectDir}/../MeshVertShader.vsh",
	"${project.projectDir}/../ShadowVertShader.vsh",
	"${project.projectDir}/../TriangleVertShader.vsh",
	"${project.projectDir}/../../../assets/GnomeToy/GnomeToy.pod",
	"${project.projectDir}/../../../assets/GnomeToy/GnomeWood.pvr",
	"${project.projectDir}/../../../assets/GnomeToy/GnomeWood_astc.pvr",
	"${project.projectDir}/../../../assets/GnomeToy/DarkWood.pvr",
	"${project.projectDir}/../../../assets/GnomeToy/DarkWood_astc.pvr",
	"${project.projectDir}/../../../assets/GnomeToy/ClearWood.pvr",
	"${project.projectDir}/../../../assets/GnomeToy/ClearWood_astc.pvr",
	)
	
	// Add a task for copying our assets from their original location (${project.projectDir}...) to the assets/ folder for packaging
	tasks.register('copyAssetsDebug', Copy) {
		from assetFiles
		into sourceSets.main.assets.srcDirs[0]
		filePermissions { unix(0664) }
	}
	
	tasks.register('copyAssetsRelease', Copy) {
		from assetFiles
		into sourceSets.main.assets.srcDirs[0]
		filePermissions { unix(0664) }
	}
}

// This block specifies dependencies required to build only the module itself
dependencies {
	// Dependency on local binaries
	implementation fileTree(dir: 'libs', include: ['*.jar'])
    implementation project(':PVRShell')
    implementation project(':PVRUtilsGles')
}



