plugins { id 'com.android.library' }

def projectDependencies = ["PVRUtilsVk", "pugixml"]

android {
namespace = "com.powervr.PVRPfx"
defaultConfig {
versionCode = 1
versionName = "1.0"
		externalNativeBuild {
			cmake {
				cppFlags "-fexceptions"
				arguments "-DANDROID_STL=c++_static", "-DPVR_PREBUILT_DEPENDENCIES=ON", "-DPVR_ENABLE_INSTALL=ON"
				targets "PVRPfx"
			}
		}
}
	externalNativeBuild {
		cmake {

			path = "../CMakeLists.txt"
}
	}
}



// This block specifies dependencies required to build only the module itself
dependencies {
    // Dependency on local binaries
    implementation fileTree(dir: 'libs', include: ['*.jar'])
    implementation project(':PVRShell')
    implementation project(':PVRUtilsVk')
    implementation project(':pugixml')
}

