var searchData=
[
  ['rasterstatecreateparam',['RasterStateCreateParam',['../structpvr_1_1api_1_1pipeline_creation_1_1_raster_state_create_param.html#acc40a248cf4a0077eefa768144176c8a',1,'pvr::api::pipelineCreation::RasterStateCreateParam']]],
  ['rayintersectionstatecreateparam',['RayIntersectionStateCreateParam',['../structpvr_1_1api_1_1pipeline_creation_1_1_ray_intersection_state_create_param.html#adaa9d375f487d4a357d71c1e946ed0b3',1,'pvr::api::pipelineCreation::RayIntersectionStateCreateParam::RayIntersectionStateCreateParam(bool occluder=true, pvr::types::VisibleFace visibleFace=pvr::types::VisibleFace::FrontBack, pvr::types::PolygonWindingOrder windingOrder=pvr::types::PolygonWindingOrder::Default, bool hasDecal=false, pvr::uint32 rayTypeVisibilityCount=0)'],['../structpvr_1_1api_1_1pipeline_creation_1_1_ray_intersection_state_create_param.html#aa33981f515887180e52393b82e5dea22',1,'pvr::api::pipelineCreation::RayIntersectionStateCreateParam::RayIntersectionStateCreateParam(bool *rayTypeVisibilities, pvr::uint32 rayTypeVisibilityCount=0, bool occluder=true, pvr::types::VisibleFace visibleFace=pvr::types::VisibleFace::FrontBack, pvr::types::PolygonWindingOrder windingOrder=pvr::types::PolygonWindingOrder::Default, bool hasDecal=false)']]],
  ['rayshaderstagecreateparam',['RayShaderStageCreateParam',['../structpvr_1_1api_1_1pipeline_creation_1_1_ray_shader_stage_create_param.html#ace4cbb262c1d8d4c5f34ebb3f2eac875',1,'pvr::api::pipelineCreation::RayShaderStageCreateParam']]],
  ['renderpass_5f',['RenderPass_',['../classpvr_1_1api_1_1impl_1_1_render_pass__.html#a9fd0bfe342f2137242b8307c33b78a3e',1,'pvr::api::impl::RenderPass_']]],
  ['renderpasscolorinfo',['RenderPassColorInfo',['../structpvr_1_1api_1_1_render_pass_color_info.html#a65323d83af04e4c62998691753ee844e',1,'pvr::api::RenderPassColorInfo::RenderPassColorInfo()'],['../structpvr_1_1api_1_1_render_pass_color_info.html#a4be084bcc9b809f6db463a6b709cdf81',1,'pvr::api::RenderPassColorInfo::RenderPassColorInfo(const ImageDataFormat &amp;format, types::LoadOp loadOpColor=types::LoadOp::Load, types::StoreOp storeOpColor=types::StoreOp::Store, pvr::uint32 numSamples=1u, pvr::types::ImageLayout initialLayout=pvr::types::ImageLayout::ColorAttachmentOptimal, pvr::types::ImageLayout finalLayout=pvr::types::ImageLayout::ColorAttachmentOptimal)']]],
  ['renderpasscreateparam',['RenderPassCreateParam',['../structpvr_1_1api_1_1_render_pass_create_param.html#ab867c84f28afa5eb6419f9139cb4be34',1,'pvr::api::RenderPassCreateParam']]],
  ['renderpassdepthstencilinfo',['RenderPassDepthStencilInfo',['../structpvr_1_1api_1_1_render_pass_depth_stencil_info.html#abe958adead4375d1c2dd7f7cfd2faf55',1,'pvr::api::RenderPassDepthStencilInfo::RenderPassDepthStencilInfo()'],['../structpvr_1_1api_1_1_render_pass_depth_stencil_info.html#a3e3554e4ead4595bcd7c1f4787f1272f',1,'pvr::api::RenderPassDepthStencilInfo::RenderPassDepthStencilInfo(const ImageDataFormat &amp;format, types::LoadOp loadOpDepth=types::LoadOp::Load, types::StoreOp storeOpDepth=types::StoreOp::Store, types::LoadOp loadOpStencil=types::LoadOp::Load, types::StoreOp storeOpStencil=types::StoreOp::Store, pvr::uint32 numSamples=1)']]],
  ['reset',['reset',['../classpvr_1_1api_1_1impl_1_1_fence__.html#a988a70eaf8cf5b55eeeb084f841874a6',1,'pvr::api::impl::Fence_::reset()'],['../classpvr_1_1api_1_1impl_1_1_event__.html#ac5eaa63c0926cd91c5cfbbc5ed92fe2e',1,'pvr::api::impl::Event_::reset()']]],
  ['resetpipeline',['resetPipeline',['../classpvr_1_1api_1_1impl_1_1_command_buffer_base__.html#ab09862df3dc41a6813b8c8841694221d',1,'pvr::api::impl::CommandBufferBase_']]]
];
