# FindPVRUtilsGles.cmake
# Finds the PVRUtilsGles library and its dependencies

set(CMAKE_MODULE_PATH ${CMAKE_CURRENT_LIST_DIR})
include(CMakeFindDependencyMacro)
include("${CMAKE_CURRENT_LIST_DIR}/../utilities/android_utils.cmake")

if(NOT TARGET PVRCore)
	find_dependency(PVRCore REQUIRED MODULE)
endif()

if(NOT TARGET PVRAssets)
	find_dependency(PVRAssets REQUIRED MODULE)
endif()

if(PVR_PREBUILT_DEPENDENCIES AND ANDROID)
    set(CMAKE_FIND_ROOT_PATH_MODE_PACKAGE BOTH)
    pvr_find_android_build_path(PVRUtilsGles_PREBUILT_DIR "${CMAKE_CURRENT_LIST_DIR}/../../framework/PVRUtils/OpenGLES/build-android" "PVRUtilsGles")
    if(PVRUtilsGles_PREBUILT_DIR)
        list(APPEND CMAKE_PREFIX_PATH "${PVRUtilsGles_PREBUILT_DIR}")
    endif()
endif()

if(NOT TARGET PVRUtilsGles)
	message(STATUS "DEBUG: PVRUtilsGles NOT a target before find_package")
	find_package(PVRUtilsGles CONFIG QUIET)
	if(PVRUtilsGles_FOUND)
		message(STATUS "DEBUG: find_package(PVRUtilsGles CONFIG) SUCCEEDED. Target exists? $<TARGET_EXISTS:PVRUtilsGles>")
		get_filename_component(PVR_FRAMEWORK_DIR "${CMAKE_CURRENT_LIST_DIR}/../../framework" ABSOLUTE)
		get_filename_component(PVR_SDK_INCLUDE_DIR "${CMAKE_CURRENT_LIST_DIR}/../../include" ABSOLUTE)
		set_property(TARGET PVRUtilsGles APPEND PROPERTY INTERFACE_INCLUDE_DIRECTORIES "${PVR_FRAMEWORK_DIR}" "${PVR_SDK_INCLUDE_DIR}")
	else()
		message(STATUS "DEBUG: find_package(PVRUtilsGles CONFIG) FAILED. Calling add_subdirectory.")
		set(PVRUtilsGles_SOURCE_DIR "${CMAKE_CURRENT_LIST_DIR}/../../framework/PVRUtils/OpenGLES")
		if(EXISTS "${PVRUtilsGles_SOURCE_DIR}/CMakeLists.txt")
			add_subdirectory("${PVRUtilsGles_SOURCE_DIR}" "${CMAKE_BINARY_DIR}/framework/PVRUtils/OpenGLES")
		else()
			message(FATAL_ERROR "PVRUtilsGles: Could not find prebuilt package AND could not find source")
		endif()
	endif()
else()
	message(STATUS "DEBUG: PVRUtilsGles IS ALREADY a target before find_package")
endif()

message(STATUS "DEBUG: PVRUtilsGles target properties:")
get_target_property(loc_debug PVRUtilsGles IMPORTED_LOCATION_DEBUG)
message(STATUS "  IMPORTED_LOCATION_DEBUG: ${loc_debug}")


if(TARGET PVRUtilsGles)
    set(PVRUtilsGles_FOUND TRUE)
endif()

if(TARGET PVRUtilsGles)
    get_target_property(_loc_debug PVRUtilsGles IMPORTED_LOCATION_DEBUG)
    if(_loc_debug AND NOT EXISTS "${_loc_debug}")
        message(STATUS "Restoring PVRUtilsGles IMPORTED_LOCATION_DEBUG")
        get_filename_component(_fw_dir "${CMAKE_CURRENT_LIST_DIR}/../../framework" ABSOLUTE)
        # Find the .a file!
        file(GLOB_RECURSE _a_file "${_fw_dir}/*/build-android/.cxx/Debug/*/${ANDROID_ABI}/libPVRUtilsGles.a")
        if(_a_file)
            list(GET _a_file 0 _a_file_path)
            set_property(TARGET PVRUtilsGles PROPERTY IMPORTED_LOCATION_DEBUG "${_a_file_path}")
        endif()
    endif()
endif()
